
// Copyright 2012 Google Inc. All rights reserved.
(function(){

var data = {
"resource": {
  "version":"13",
  "macros":[{
      "function":"__e"
    },{
      "function":"__gas",
      "vtp_cookieDomain":"auto",
      "vtp_doubleClick":false,
      "vtp_setTrackerName":false,
      "vtp_useDebugVersion":false,
      "vtp_useHashAutoLink":false,
      "vtp_decorateFormsAutoLink":false,
      "vtp_enableLinkId":false,
      "vtp_enableEcommerce":false,
      "vtp_trackingId":"UA-6671908-2",
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"viewPixelImg"
    },{
      "function":"__u",
      "vtp_component":"URL"
    },{
      "function":"__u",
      "vtp_component":"HOST"
    },{
      "function":"__u",
      "vtp_component":"PATH"
    },{
      "function":"__f",
      "vtp_component":"URL"
    },{
      "function":"__e"
    }],
  "tags":[{
      "function":"__ua",
      "once_per_event":true,
      "vtp_overrideGaSettings":false,
      "vtp_trackType":"TRACK_PAGEVIEW",
      "vtp_gaSettings":["macro",1],
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "tag_id":1
    },{
      "function":"__qcm",
      "once_per_event":true,
      "vtp_pcode":"p-f8oruOqDFlMeI",
      "tag_id":2
    },{
      "function":"__csm",
      "once_per_event":true,
      "vtp_clientId":"7770950",
      "tag_id":3
    },{
      "function":"__img",
      "once_per_event":true,
      "vtp_useCacheBuster":false,
      "vtp_url":["escape",["macro",2],14,3],
      "tag_id":6
    },{
      "function":"__html",
      "once_per_load":true,
      "vtp_html":"        \u003Cscript type=\"text\/gtmscript\"\u003E!function(b,e,f,g,a,c,d){b.fbq||(a=b.fbq=function(){a.callMethod?a.callMethod.apply(a,arguments):a.queue.push(arguments)},b._fbq||(b._fbq=a),a.push=a,a.loaded=!0,a.version=\"2.0\",a.queue=[],c=e.createElement(f),c.async=!0,c.src=g,d=e.getElementsByTagName(f)[0],d.parentNode.insertBefore(c,d))}(window,document,\"script\",\"\/\/connect.facebook.net\/en_US\/fbevents.js\");fbq(\"init\",\"742377892535530\");fbq(\"track\",\"PageView\");\"?reg\"===document.location.search\u0026\u0026fbq(\"track\",\"CompleteRegistration\");\u003C\/script\u003E\n        \u003Cnoscript\u003E\u003Cimg height=\"1\" width=\"1\" style=\"display:none\" src=\"https:\/\/www.facebook.com\/tr?id=742377892535530\u0026amp;ev=PageView\u0026amp;noscript=1\"\u003E\u003C\/noscript\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":4
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\"\u003Evar _comscore=_comscore||[];_comscore.push({c1:\"2\",c2:\"7770950\",c3:\"8\",c4:\"http%3A%2F%2Fimgur.com%2F\"});_comscore.push({c1:\"8\",c2:\"7770950\",c3:\"8\",c4:\"http%3A%2F%2Fimgur.com%2F\"});\nfunction udm_(b,t){var q=\"comScore\\x3d\",e=document,l=e.cookie,u=\"\",r=\"indexOf\",m=\"substring\",v=\"length\",g=2048,n,p=\"\\x26ns_\",a=\"\\x26\",c,w=window,f=w.encodeURIComponent||escape;if(l[r](q)+1){var k=0;l=l.split(\";\");for(c=l[v];k\u003Cc;k++){var d=l[k][r](q);d+1\u0026\u0026(u=a+unescape(l[k][m](d+q[v])))}}b+=p+\"_t\\x3d\"+ +new Date+p+\"c\\x3d\"+(e.characterSet||e.defaultCharset||\"\")+\"\\x26c8\\x3d\"+f(e.title)+u+\"\\x26c7\\x3d\"+f(e.URL)+\"\\x26c9\\x3d\"+f(e.referrer);b[v]\u003Eg\u0026\u00260\u003Cb[r](a)\u0026\u0026(n=b[m](0,g-8).lastIndexOf(a),b=(b[m](0,n)+p+\n\"cut\\x3d\"+f(b[m](n+1)))[m](0,g));e.images?(d=new Image,w.ns_p||(ns_p=d),\"function\"==typeof t\u0026\u0026(d.onload=d.onerror=t),d.src=b):e.write(\"\\x3c\",\"p\",\"\\x3e\\x3c\",'img src\\x3d\"',b,'\" height\\x3d\"1\" width\\x3d\"1\" alt\\x3d\"*\"',\"\\x3e\\x3c\",\"\/p\",\"\\x3e\")}\"undefined\"==typeof _comscore\u0026\u0026(_comscore=[]);\n(function(){var b=\"length\",t=self,q=t.encodeURIComponent?encodeURIComponent:escape,e=\".scorecardresearch.com\",l=\"\/\/app\"+e+\"\/s2e\/invite\",u=Math,r=\"script\",m=\"width\",v=\/c2=(\\d*)\u0026\/,g,n=function(a){if(a){var c=[];var g=0,f=\"\";for(h in a){var k=typeof a[h];if(\"string\"==k||\"number\"==k)c[c[b]]=h+\"\\x3d\"+q(a[h]),\"c2\"==h?f=a[h]:\"c1\"==h\u0026\u0026(g=1)}if(!(0\u003E=c[b]||\"\"==f)){var d=a.options||{};d.d=d.d||document;if(\"string\"==typeof d.url_append){a=d.url_append.replace(\/\u0026amp;\/,\"\\x26\").split(\"\\x26\");var h=0;for(k=a[b];h\u003C\nk;h++)f=a[h].split(\"\\x3d\"),2==f[b]\u0026\u0026(c[c[b]]=f[0]+\"\\x3d\"+q(f[1]))}c=[\"http\",\"s\"==d.d.URL.charAt(4)?\"s:\/\/sb\":\":\/\/b\",e,\"\/b?\",g?\"\":\"c1\\x3d2\\x26\",c.join(\"\\x26\").replace(\/\u0026$\/,\"\")];udm_(c.join(\"\"),function(){var a=d;if(!(0\u003Ethis.src.indexOf(\"c1\\x3d2\"))\u0026\u0026a.d.createElement\u0026\u0026(a.force_script_extension||2==this[m]\u0026\u0026this.height\u003Eu.round(100*u.random()))){var b=a.d.createElement(r),c=a.d.getElementsByTagName(r)[0];a=[a.script_extension_url||l,\"?c2\\x3d\",this.src.match(v)[1]].join(\"\");c\u0026\u0026(b.src=a,b.async=!0,c.parentNode.insertBefore(b,\nc))}})}}},p=function(a){a=a||_comscore;for(var c=0,e=a[b];c\u003Ce;c++)n(a[c]);_comscore=[]};p();(g=t.COMSCORE)?(g.purge=p,g.beacon=n):COMSCORE={purge:p,beacon:n}})();\u003C\/script\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":5
    }],
  "predicates":[{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"next-post"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"load-more"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"mobile-next-post"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"gtm.js"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"track-view-pixel"
    }],
  "rules":[
    [["if",0],["add",0,1,5]],
    [["if",1],["add",0]],
    [["if",2],["add",0,1,2]],
    [["if",3],["add",0,1,2,4]],
    [["if",4],["add",3]]]
},
"runtime":[
[],[]
]
};
var da=this,ha=function(){if(null===ea){var a;a:{var b=da.document,c=b.querySelector&&b.querySelector("script[nonce]");if(c){var d=c.nonce||c.getAttribute("nonce");if(d&&fa.test(d)){a=d;break a}}a=null}ea=a||""}return ea},fa=/^[\w+/_-]+[=]{0,2}$/,ea=null,ia=function(a,b){function c(){}c.prototype=b.prototype;a.rf=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ye=function(a,c,g){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,
d)}};var f=function(a,b){this.C=a;this.wd=b};f.prototype.Kd=function(){return this.C};f.prototype.getType=f.prototype.Kd;f.prototype.getData=function(){return this.wd};f.prototype.getData=f.prototype.getData;var ka=function(a){return"number"===typeof a&&0<=a&&isFinite(a)&&0===a%1||"string"===typeof a&&"-"!==a[0]&&a===""+parseInt(a,10)},la=function(){this.ka={};this.Aa=!1};la.prototype.get=function(a){return this.ka["dust."+a]};la.prototype.set=function(a,b){!this.Aa&&(this.ka["dust."+a]=b)};la.prototype.has=function(a){return this.ka.hasOwnProperty("dust."+a)};var ma=function(a){var b=[],c;for(c in a.ka)a.ka.hasOwnProperty(c)&&b.push(c.substr(5));return b};
la.prototype.remove=function(a){!this.Aa&&delete this.ka["dust."+a]};la.prototype.M=function(){this.Aa=!0};var v=function(a){this.na=new la;this.i=[];a=a||[];for(var b in a)a.hasOwnProperty(b)&&(ka(b)?this.i[Number(b)]=a[Number(b)]:this.na.set(b,a[b]))};v.prototype.toString=function(){for(var a=[],b=0;b<this.i.length;b++){var c=this.i[b];null===c||void 0===c?a.push(""):a.push(c.toString())}return a.join(",")};v.prototype.set=function(a,b){if("length"==a){if(!ka(b))throw"RangeError: Length property must be a valid integer.";this.i.length=Number(b)}else ka(a)?this.i[Number(a)]=b:this.na.set(a,b)};
v.prototype.set=v.prototype.set;v.prototype.get=function(a){return"length"==a?this.length():ka(a)?this.i[Number(a)]:this.na.get(a)};v.prototype.get=v.prototype.get;v.prototype.length=function(){return this.i.length};v.prototype.T=function(){for(var a=ma(this.na),b=0;b<this.i.length;b++)a.push(b+"");return new v(a)};v.prototype.getKeys=v.prototype.T;v.prototype.remove=function(a){ka(a)?delete this.i[Number(a)]:this.na.remove(a)};v.prototype.remove=v.prototype.remove;v.prototype.pop=function(){return this.i.pop()};
v.prototype.pop=v.prototype.pop;v.prototype.push=function(a){return this.i.push.apply(this.i,Array.prototype.slice.call(arguments))};v.prototype.push=v.prototype.push;v.prototype.shift=function(){return this.i.shift()};v.prototype.shift=v.prototype.shift;v.prototype.splice=function(a,b,c){return new v(this.i.splice.apply(this.i,arguments))};v.prototype.splice=v.prototype.splice;v.prototype.unshift=function(a){return this.i.unshift.apply(this.i,Array.prototype.slice.call(arguments))};
v.prototype.unshift=v.prototype.unshift;v.prototype.has=function(a){return ka(a)&&this.i.hasOwnProperty(a)||this.na.has(a)};var na=function(){function a(a,b){c[a]=b}function b(){c={};g=!1}var c={},d,e={},g=!1,h={add:a,Wb:function(a,b,c){e[a]||(e[a]={});e[a][b]=c},create:function(e){var h={add:a,assert:function(a,b){if(!g){var h=c[a]||d;h&&h.apply(e,Array.prototype.slice.call(arguments,0))}},reset:b};h.add=h.add;h.assert=h.assert;h.reset=h.reset;return h},xc:function(a){return e[a]?(b(),c=e[a],!0):!1},oa:function(a){d=a},reset:b,Hc:function(a){g=a}};h.add=h.add;h.addToCache=h.Wb;h.loadFromCache=h.xc;h.registerDefaultPermission=
h.oa;h.reset=h.reset;h.setPermitAllAsserts=h.Hc;return h};var oa=function(){function a(a,c){if(b[a]){if(b[a].Pa+c>b[a].max)throw Error("Quota exceeded");b[a].Pa+=c}}var b={},c=void 0,d=void 0,e={ke:function(a){c=a},Xb:function(){c&&a(c,1)},me:function(a){d=a},W:function(b){d&&a(d,b)},He:function(a,c){b[a]=b[a]||{Pa:0};b[a].max=c},Jd:function(a){return b[a]&&b[a].Pa||0},reset:function(){b={}},qd:a};e.onFnConsume=e.ke;e.consumeFn=e.Xb;e.onStorageConsume=e.me;e.consumeStorage=e.W;e.setMax=e.He;e.getConsumed=e.Jd;e.reset=e.reset;e.consume=e.qd;return e};var pa=function(a,b,c){this.N=a;this.I=b;this.Z=c;this.i=new la};pa.prototype.add=function(a,b){this.i.Aa||(this.N.W(("string"===typeof a?a.length:1)+("string"===typeof b?b.length:1)),this.i.set(a,b))};pa.prototype.add=pa.prototype.add;pa.prototype.set=function(a,b){this.i.Aa||(this.Z&&this.Z.has(a)?this.Z.set(a,b):(this.N.W(("string"===typeof a?a.length:1)+("string"===typeof b?b.length:1)),this.i.set(a,b)))};pa.prototype.set=pa.prototype.set;
pa.prototype.get=function(a){return this.i.has(a)?this.i.get(a):this.Z?this.Z.get(a):void 0};pa.prototype.get=pa.prototype.get;pa.prototype.has=function(a){return!!this.i.has(a)||!(!this.Z||!this.Z.has(a))};pa.prototype.has=pa.prototype.has;pa.prototype.K=function(){return this.N};pa.prototype.M=function(){this.i.M()};var qa=function(){},ra=function(a){return"function"==typeof a},sa=function(a){return"string"==typeof a},ta=function(a){return"number"==typeof a&&!isNaN(a)},ua=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},va=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},xa=function(a,b){if(!ta(a)||!ta(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},ya=function(a){return Math.round(Number(a))||
0},Aa=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Ba=function(a){var b=[];if(ua(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},Ca=function(){return new Date},Da=function(){this.prefix="gtm.";this.values={}};Da.prototype.set=function(a,b){this.values[this.prefix+a]=b};Da.prototype.get=function(a){return this.values[this.prefix+a]};Da.prototype.contains=function(a){return void 0!==this.get(a)};
var Ea=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Fa=function(a){var b=!1;return function(){if(!b)try{a()}catch(c){}b=!0}},Ga=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},Ha=function(a){for(var b in a)if(a.hasOwnProperty(b))return!0;return!1};var w=function(a,b){la.call(this);this.yc=a;this.Gd=b};ia(w,la);var Ja=function(a,b){for(var c,d=0;d<b.length&&!(c=Ia(a,b[d]),c instanceof f);d++);return c},Ia=function(a,b){var c=a.get(String(b[0]));if(!(c&&c instanceof w))throw"Attempting to execute non-function "+b[0]+".";return c.o.apply(c,[a].concat(b.slice(1)))};w.prototype.toString=function(){return this.yc};w.prototype.getName=function(){return this.yc};w.prototype.getName=w.prototype.getName;w.prototype.T=function(){return new v(ma(this))};
w.prototype.getKeys=w.prototype.T;w.prototype.o=function(a,b){var c,d={F:function(){return a},evaluate:function(b){var c=a;return ua(b)?Ia(c,b):b},xa:function(b){return Ja(a,b)},K:function(){return a.K()},kb:function(){c||(c=a.I.create(d));return c}};a.K().Xb();return this.Gd.apply(d,Array.prototype.slice.call(arguments,1))};w.prototype.invoke=w.prototype.o;var Ka=function(){la.call(this)};ia(Ka,la);Ka.prototype.T=function(){return new v(ma(this))};Ka.prototype.getKeys=Ka.prototype.T;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var La=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Ma=function(a){if(null==a)return String(a);var b=La.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Na=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Oa=function(a){if(!a||"object"!=Ma(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Na(a,"constructor")&&!Na(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Na(a,b)},Pa=function(a,b){var c=b||("array"==Ma(a)?[]:{}),d;for(d in a)if(Na(a,d)){var e=a[d];"array"==Ma(e)?("array"!=Ma(c[d])&&(c[d]=[]),c[d]=Pa(e,c[d])):Oa(e)?(Oa(c[d])||(c[d]={}),c[d]=Pa(e,c[d])):c[d]=e}return c};var Qa=function(a){if(a instanceof v){for(var b=[],c=a.length(),d=0;d<c;d++)a.has(d)&&(b[d]=Qa(a.get(d)));return b}if(a instanceof Ka){for(var e={},g=a.T(),h=g.length(),k=0;k<h;k++)e[g.get(k)]=Qa(a.get(g.get(k)));return e}return a instanceof w?function(){for(var b=Array.prototype.slice.call(arguments,0),c=0;c<b.length;c++)b[c]=Ra(b[c]);var d=new pa(oa(),na());return Qa(a.o.apply(a,[d].concat(b)))}:a},Ra=function(a){if(ua(a)){for(var b=[],c=0;c<a.length;c++)a.hasOwnProperty(c)&&(b[c]=Ra(a[c]));return new v(b)}if(Oa(a)){var d=
new Ka,e;for(e in a)a.hasOwnProperty(e)&&d.set(e,Ra(a[e]));return d}if("function"===typeof a)return new w("",function(b){for(var c=Array.prototype.slice.call(arguments,0),d=0;d<c.length;d++)c[d]=Qa(this.evaluate(c[d]));return Ra(a.apply(a,c))});var g=typeof a;if(null===a||"string"===g||"number"===g||"boolean"===g)return a};var Sa={control:function(a,b){return new f(a,this.evaluate(b))},fn:function(a,b,c){var d=this.F(),e=this.evaluate(b);if(!(e instanceof v))throw"Error: non-List value given for Fn argument names.";var g=Array.prototype.slice.call(arguments,2);this.K().W(a.length+g.length);return new w(a,function(){return function(a){for(var b=new pa(d.N,d.I,d),c=Array.prototype.slice.call(arguments,0),h=0;h<c.length;h++)if(c[h]=this.evaluate(c[h]),c[h]instanceof f)return c[h];for(var n=e.get("length"),p=0;p<n;p++)p<
c.length?b.set(e.get(p),c[p]):b.set(e.get(p),void 0);b.set("arguments",new v(c));var q=Ja(b,g);if(q instanceof f)return"return"===q.C?q.getData():q}}())},list:function(a){var b=this.K();b.W(arguments.length);for(var c=new v,d=0;d<arguments.length;d++){var e=this.evaluate(arguments[d]);"string"===typeof e&&b.W(e.length?e.length-1:0);c.push(e)}return c},map:function(a){for(var b=this.K(),c=new Ka,d=0;d<arguments.length-1;d+=2){var e=this.evaluate(arguments[d])+"",g=this.evaluate(arguments[d+1]),h=e.length;
h+="string"===typeof g?g.length:1;b.W(h);c.set(e,g)}return c},undefined:function(){}};var x=function(){this.N=oa();this.I=na();this.ya=new pa(this.N,this.I)};x.prototype.V=function(a,b){var c=new w(a,b);c.M();this.ya.set(a,c)};x.prototype.addInstruction=x.prototype.V;x.prototype.Vb=function(a,b){Sa.hasOwnProperty(a)&&this.V(b||a,Sa[a])};x.prototype.addNativeInstruction=x.prototype.Vb;x.prototype.K=function(){return this.N};x.prototype.getQuota=x.prototype.K;x.prototype.Wa=function(){this.N=oa();this.ya.N=this.N};x.prototype.resetQuota=x.prototype.Wa;
x.prototype.Ee=function(){this.I=na();this.ya.I=this.I};x.prototype.resetPermissions=x.prototype.Ee;x.prototype.L=function(a,b){var c=Array.prototype.slice.call(arguments,0);return this.yb(c)};x.prototype.execute=x.prototype.L;x.prototype.yb=function(a){for(var b,c=0;c<arguments.length;c++){var d=Ia(this.ya,arguments[c]);b=d instanceof f||d instanceof w||d instanceof v||d instanceof Ka||null===d||void 0===d||"string"===typeof d||"number"===typeof d||"boolean"===typeof d?d:void 0}return b};
x.prototype.run=x.prototype.yb;x.prototype.M=function(){this.ya.M()};x.prototype.makeImmutable=x.prototype.M;var Ta=function(a){for(var b=[],c=0;c<a.length();c++)a.has(c)&&(b[c]=a.get(c));return b};var Ua={Le:"concat every filter forEach hasOwnProperty indexOf join lastIndexOf map pop push reduce reduceRight reverse shift slice some sort splice unshift toString".split(" "),concat:function(a,b){for(var c=[],d=0;d<this.length();d++)c.push(this.get(d));for(d=1;d<arguments.length;d++)if(arguments[d]instanceof v)for(var e=arguments[d],g=0;g<e.length();g++)c.push(e.get(g));else c.push(arguments[d]);return new v(c)},every:function(a,b){for(var c=this.length(),d=0;d<this.length()&&d<c;d++)if(this.has(d)&&
!b.o(a,this.get(d),d,this))return!1;return!0},filter:function(a,b){for(var c=this.length(),d=[],e=0;e<this.length()&&e<c;e++)this.has(e)&&b.o(a,this.get(e),e,this)&&d.push(this.get(e));return new v(d)},forEach:function(a,b){for(var c=this.length(),d=0;d<this.length()&&d<c;d++)this.has(d)&&b.o(a,this.get(d),d,this)},hasOwnProperty:function(a,b){return this.has(b)},indexOf:function(a,b,c){var d=this.length(),e=void 0===c?0:Number(c);0>e&&(e=Math.max(d+e,0));for(var g=e;g<d;g++)if(this.has(g)&&this.get(g)===
b)return g;return-1},join:function(a,b){for(var c=[],d=0;d<this.length();d++)c.push(this.get(d));return c.join(b)},lastIndexOf:function(a,b,c){var d=this.length(),e=d-1;void 0!==c&&(e=0>c?d+c:Math.min(c,e));for(var g=e;0<=g;g--)if(this.has(g)&&this.get(g)===b)return g;return-1},map:function(a,b){for(var c=this.length(),d=[],e=0;e<this.length()&&e<c;e++)this.has(e)&&(d[e]=b.o(a,this.get(e),e,this));return new v(d)},pop:function(){return this.pop()},push:function(a,b){return this.push.apply(this,Array.prototype.slice.call(arguments,
1))},reduce:function(a,b,c){var d=this.length(),e,g;if(void 0!==c)e=c,g=0;else{if(0==d)throw"TypeError: Reduce on List with no elements.";for(var h=0;h<d;h++)if(this.has(h)){e=this.get(h);g=h+1;break}if(h==d)throw"TypeError: Reduce on List with no elements.";}for(h=g;h<d;h++)this.has(h)&&(e=b.o(a,e,this.get(h),h,this));return e},reduceRight:function(a,b,c){var d=this.length(),e,g;if(void 0!==c)e=c,g=d-1;else{if(0==d)throw"TypeError: ReduceRight on List with no elements.";for(var h=1;h<=d;h++)if(this.has(d-
h)){e=this.get(d-h);g=d-(h+1);break}if(h>d)throw"TypeError: ReduceRight on List with no elements.";}for(h=g;0<=h;h--)this.has(h)&&(e=b.o(a,e,this.get(h),h,this));return e},reverse:function(){for(var a=Ta(this),b=a.length-1,c=0;0<=b;b--,c++)a.hasOwnProperty(b)?this.set(c,a[b]):this.remove(c);return this},shift:function(){return this.shift()},slice:function(a,b,c){var d=this.length();void 0===b&&(b=0);b=0>b?Math.max(d+b,0):Math.min(b,d);c=void 0===c?d:0>c?Math.max(d+c,0):Math.min(c,d);c=Math.max(b,
c);for(var e=[],g=b;g<c;g++)e.push(this.get(g));return new v(e)},some:function(a,b){for(var c=this.length(),d=0;d<this.length()&&d<c;d++)if(this.has(d)&&b.o(a,this.get(d),d,this))return!0;return!1},sort:function(a,b){var c=Ta(this);void 0===b?c.sort():c.sort(function(c,d){return Number(b.o(a,c,d))});for(var d=0;d<c.length;d++)c.hasOwnProperty(d)?this.set(d,c[d]):this.remove(d)},splice:function(a,b,c,d){return this.splice.apply(this,Array.prototype.splice.call(arguments,1,arguments.length-1))},toString:function(){return this.toString()},
unshift:function(a,b){return this.unshift.apply(this,Array.prototype.slice.call(arguments,1))}};var y={oc:{ADD:0,AND:1,APPLY:2,ASSIGN:3,BREAK:4,CASE:5,CONTINUE:6,CONTROL:49,CREATE_ARRAY:7,CREATE_OBJECT:8,DEFAULT:9,DEFN:50,DIVIDE:10,DO:11,EQUALS:12,EXPRESSION_LIST:13,FN:51,FOR:14,FOR_IN:47,GET:15,GET_CONTAINER_VARIABLE:48,GET_INDEX:16,GET_PROPERTY:17,GREATER_THAN:18,GREATER_THAN_EQUALS:19,IDENTITY_EQUALS:20,IDENTITY_NOT_EQUALS:21,IF:22,LESS_THAN:23,LESS_THAN_EQUALS:24,MODULUS:25,MULTIPLY:26,NEGATE:27,NOT:28,NOT_EQUALS:29,NULL:45,OR:30,PLUS_EQUALS:31,POST_DECREMENT:32,POST_INCREMENT:33,PRE_DECREMENT:34,
PRE_INCREMENT:35,QUOTE:46,RETURN:36,SET_PROPERTY:43,SUBTRACT:37,SWITCH:38,TERNARY:39,TYPEOF:40,UNDEFINED:44,VAR:41,WHILE:42}},Va="charAt concat indexOf lastIndexOf match replace search slice split substring toLowerCase toLocaleLowerCase toString toUpperCase toLocaleUpperCase trim".split(" "),Wa=new f("break"),Xa=new f("continue");y.add=function(a,b){return this.evaluate(a)+this.evaluate(b)};y.and=function(a,b){return this.evaluate(a)&&this.evaluate(b)};
y.apply=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);if(!(c instanceof v))throw"Error: Non-List argument given to Apply instruction.";if(null===a||void 0===a)throw"TypeError: Can't read property "+b+" of "+a+".";if("boolean"==typeof a||"number"==typeof a){if("toString"==b)return a.toString();throw"TypeError: "+a+"."+b+" is not a function.";}if("string"==typeof a){if(0<=va(Va,b))return Ra(a[b].apply(a,Ta(c)));throw"TypeError: "+b+" is not a function";}if(a instanceof v){if(a.has(b)){var d=
a.get(b);if(d instanceof w){var e=Ta(c);e.unshift(this.F());return d.o.apply(d,e)}throw"TypeError: "+b+" is not a function";}if(0<=va(Ua.Le,b))return e=Ta(c),e.unshift(this.F()),Ua[b].apply(a,e)}if(a instanceof w||a instanceof Ka){if(a.has(b)){d=a.get(b);if(d instanceof w)return e=Ta(c),e.unshift(this.F()),d.o.apply(d,e);throw"TypeError: "+b+" is not a function";}if("toString"==b)return a instanceof w?a.getName():a.toString();if("hasOwnProperty"==b)return a.has.apply(a,Ta(c))}throw"TypeError: Object has no '"+
b+"' property.";};y.assign=function(a,b){a=this.evaluate(a);if("string"!=typeof a)throw"Invalid key name given for assignment.";var c=this.F();if(!c.has(a))throw"Attempting to assign to undefined value "+b;var d=this.evaluate(b);c.set(a,d);return d};y["break"]=function(){return Wa};y["case"]=function(a){for(var b=this.evaluate(a),c=0;c<b.length;c++){var d=this.evaluate(b[c]);if(d instanceof f)return d}};y["continue"]=function(){return Xa};
y.xd=function(a,b,c){var d=new v;b=this.evaluate(b);for(var e=0;e<b.length;e++)d.push(b[e]);var g=[y.oc.FN,a,d].concat(Array.prototype.splice.call(arguments,2,arguments.length-2));this.F().set(a,this.evaluate(g))};y.Ad=function(a,b){return this.evaluate(a)/this.evaluate(b)};y.Dd=function(a,b){return this.evaluate(a)==this.evaluate(b)};y.Ed=function(a){for(var b,c=0;c<arguments.length;c++)b=this.evaluate(arguments[c]);return b};
y.Hd=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);var d=this.F();if("string"==typeof b)for(var e=0;e<b.length;e++){d.set(a,e);var g=this.xa(c);if(g instanceof f){if("break"==g.C)break;if("return"==g.C)return g}}else if(b instanceof Ka||b instanceof v||b instanceof w){var h=b.T(),k=h.length();for(e=0;e<k;e++)if(d.set(a,h.get(e)),g=this.xa(c),g instanceof f){if("break"==g.C)break;if("return"==g.C)return g}}};y.get=function(a){return this.F().get(this.evaluate(a))};
y.hc=function(a,b){var c;a=this.evaluate(a);b=this.evaluate(b);if(void 0===a||null===a)throw"TypeError: cannot access property of "+a+".";a instanceof Ka||a instanceof v||a instanceof w?c=a.get(b):"string"==typeof a&&("length"==b?c=a.length:ka(b)&&(c=a[b]));return c};y.Ld=function(a,b){return this.evaluate(a)>this.evaluate(b)};y.Md=function(a,b){return this.evaluate(a)>=this.evaluate(b)};y.Td=function(a,b){return this.evaluate(a)===this.evaluate(b)};y.Ud=function(a,b){return this.evaluate(a)!==this.evaluate(b)};
y["if"]=function(a,b,c){var d=[];this.evaluate(a)?d=this.evaluate(b):c&&(d=this.evaluate(c));var e=this.xa(d);if(e instanceof f)return e};y.be=function(a,b){return this.evaluate(a)<this.evaluate(b)};y.ce=function(a,b){return this.evaluate(a)<=this.evaluate(b)};y.ee=function(a,b){return this.evaluate(a)%this.evaluate(b)};y.multiply=function(a,b){return this.evaluate(a)*this.evaluate(b)};y.fe=function(a){return-this.evaluate(a)};y.he=function(a){return!this.evaluate(a)};
y.ie=function(a,b){return this.evaluate(a)!=this.evaluate(b)};y["null"]=function(){return null};y.or=function(a,b){return this.evaluate(a)||this.evaluate(b)};y.Dc=function(a,b){var c=this.evaluate(a);this.evaluate(b);return c};y.Ec=function(a){return this.evaluate(a)};y.quote=function(a){return Array.prototype.slice.apply(arguments)};y["return"]=function(a){return new f("return",this.evaluate(a))};
y.setProperty=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);if(null===a||void 0===a)throw"TypeError: Can't set property "+b+" of "+a+".";(a instanceof w||a instanceof v||a instanceof Ka)&&a.set(b,c);return c};y.Ke=function(a,b){return this.evaluate(a)-this.evaluate(b)};
y["switch"]=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);if(!ua(b)||!ua(c))throw"Error: Malformed switch instruction.";for(var d,e=!1,g=0;g<b.length;g++)if(e||a===this.evaluate(b[g]))if(d=this.evaluate(c[g]),d instanceof f){var h=d.C;if("break"==h)return;if("return"==h||"continue"==h)return d}else e=!0;if(c.length==b.length+1&&(d=this.evaluate(c[c.length-1]),d instanceof f&&("return"==d.C||"continue"==d.C)))return d};
y.Me=function(a,b,c){return this.evaluate(a)?this.evaluate(b):this.evaluate(c)};y["typeof"]=function(a){a=this.evaluate(a);return a instanceof w?"function":typeof a};y.undefined=function(){};y["var"]=function(a){for(var b=this.F(),c=0;c<arguments.length;c++){var d=arguments[c];"string"!=typeof d||b.add(d,void 0)}};
y["while"]=function(a,b,c,d){var e,g=this.evaluate(d);if(this.evaluate(c)&&(e=this.xa(g),e instanceof f)){if("break"==e.C)return;if("return"==e.C)return e}for(;this.evaluate(a);){e=this.xa(g);if(e instanceof f){if("break"==e.C)break;if("return"==e.C)return e}this.evaluate(b)}};var ab=function(){this.nc=!1;this.H=new x;Ya(this);this.nc=!0};ab.prototype.Zd=function(){return this.nc};ab.prototype.isInitialized=ab.prototype.Zd;ab.prototype.L=function(a){this.H.I.xc(String(a[0]))||(this.H.I.reset(),this.H.I.Hc(!0));return this.H.yb(a)};ab.prototype.execute=ab.prototype.L;ab.prototype.M=function(){this.H.M()};ab.prototype.makeImmutable=ab.prototype.M;
var Ya=function(a){function b(a,b){e.H.Vb(a,String(b))}function c(a,b){e.H.V(String(d[a]),b)}var d=y.oc,e=a;b("control",d.CONTROL);b("fn",d.FN);b("list",d.CREATE_ARRAY);b("map",d.CREATE_OBJECT);b("undefined",d.UNDEFINED);c("ADD",y.add);c("AND",y.and);c("APPLY",y.apply);c("ASSIGN",y.assign);c("BREAK",y["break"]);c("CASE",y["case"]);c("CONTINUE",y["continue"]);c("DEFAULT",y["case"]);c("DEFN",y.xd);c("DIVIDE",y.Ad);c("EQUALS",y.Dd);c("EXPRESSION_LIST",y.Ed);c("FOR_IN",y.Hd);c("GET",y.get);c("GET_INDEX",
y.hc);c("GET_PROPERTY",y.hc);c("GREATER_THAN",y.Ld);c("GREATER_THAN_EQUALS",y.Md);c("IDENTITY_EQUALS",y.Td);c("IDENTITY_NOT_EQUALS",y.Ud);c("IF",y["if"]);c("LESS_THAN",y.be);c("LESS_THAN_EQUALS",y.ce);c("MODULUS",y.ee);c("MULTIPLY",y.multiply);c("NEGATE",y.fe);c("NOT",y.he);c("NOT_EQUALS",y.ie);c("NULL",y["null"]);c("OR",y.or);c("POST_DECREMENT",y.Dc);c("POST_INCREMENT",y.Dc);c("PRE_DECREMENT",y.Ec);c("PRE_INCREMENT",y.Ec);c("QUOTE",y.quote);c("RETURN",y["return"]);c("SET_PROPERTY",y.setProperty);
c("SUBTRACT",y.Ke);c("SWITCH",y["switch"]);c("TERNARY",y.Me);c("TYPEOF",y["typeof"]);c("VAR",y["var"]);c("WHILE",y["while"])};ab.prototype.V=function(a,b){this.H.V(a,b)};ab.prototype.addInstruction=ab.prototype.V;ab.prototype.K=function(){return this.H.K()};ab.prototype.getQuota=ab.prototype.K;ab.prototype.Wa=function(){this.H.Wa()};ab.prototype.resetQuota=ab.prototype.Wa;ab.prototype.oa=function(a){this.H.I.oa(a)};ab.prototype.Na=function(a,b,c){this.H.I.Wb(a,b,c)};var bb=function(){this.Sa={}};bb.prototype.get=function(a){return this.Sa.hasOwnProperty(a)?this.Sa[a]:void 0};bb.prototype.add=function(a,b){if(this.Sa.hasOwnProperty(a))throw"Attempting to add a function which already exists: "+a+".";var c=new w(a,function(){for(var a=Array.prototype.slice.call(arguments,0),c=0;c<a.length;c++)a[c]=this.evaluate(a[c]);return b.apply(this,a)});c.M();this.Sa[a]=c};bb.prototype.addAll=function(a){for(var b in a)a.hasOwnProperty(b)&&this.add(b,a[b])};var z=window,B=document,cb=navigator,db=function(a,b){var c=z[a];z[a]=void 0===c?b:c;return z[a]},eb=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},fb=function(a,b,c){var d=B.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;eb(d,b);c&&(d.onerror=c);ha()&&d.setAttribute("nonce",ha());var e=B.getElementsByTagName("script")[0]||B.body||B.head;e.parentNode.insertBefore(d,e);return d},
gb=function(a,b){var c=B.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";var d=B.body&&B.body.lastChild||B.body||B.head;d.parentNode.insertBefore(c,d);eb(c,b);void 0!==a&&(c.src=a);return c},F=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},hb=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},ib=function(a,b,
c,d){a.removeEventListener?a.removeEventListener(b,c,!!d):a.detachEvent&&a.detachEvent("on"+b,c)},H=function(a){z.setTimeout(a,0)},lb=function(a){var b=B.getElementById(a);if(b&&kb(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(kb(document.all[a][c],"id")==a)return document.all[a][c];return b},kb=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},mb=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=
b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},nb=function(a){var b=B.createElement("div");b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},ob=function(a){cb.sendBeacon&&cb.sendBeacon(a)||F(a)};var pb=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;var qb=/:[0-9]+$/,rb=function(a,b,c){for(var d=a.split("&"),e=0;e<d.length;e++){var g=d[e].split("=");if(decodeURIComponent(g[0]).replace(/\+/g," ")==b){var h=g.slice(1).join("=");return c?h:decodeURIComponent(h).replace(/\+/g," ")}}},sb=function(a,b,c,d,e){var g,h=function(a){return a?a.replace(":","").toLowerCase():""},k=h(a.protocol)||h(z.location.protocol);b&&(b=String(b).toLowerCase());switch(b){case "protocol":g=k;break;case "host":g=(a.hostname||z.location.hostname).replace(qb,"").toLowerCase();
if(c){var l=/^www\d*\./.exec(g);l&&l[0]&&(g=g.substr(l[0].length))}break;case "port":g=String(Number(a.hostname?a.port:z.location.port)||("http"==k?80:"https"==k?443:""));break;case "path":g="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var m=g.split("/");0<=va(d||[],m[m.length-1])&&(m[m.length-1]="");g=m.join("/");break;case "query":g=a.search.replace("?","");e&&(g=rb(g,e));break;case "extension":var n=a.pathname.split(".");g=1<n.length?n[n.length-1]:"";g=g.split("/")[0];break;case "fragment":g=
a.hash.replace("#","");break;default:g=a&&a.href}return g},tb=function(a){var b="";a&&a.href&&(b=a.hash?a.href.replace(a.hash,""):a.href);return b},N=function(a){var b=document.createElement("a");a&&(pb.test(a),b.href=a);var c=b.pathname;"/"!==c[0]&&(c="/"+c);var d=b.hostname.replace(qb,"");return{href:b.href,protocol:b.protocol,host:b.host,hostname:d,pathname:c,search:b.search,hash:b.hash,port:b.port}};var wb=function(){this.Va=new ab;var a=new bb;a.addAll(ub());vb(this,function(b){return a.get(b)})},ub=function(){return{callInWindow:xb,callLater:yb,copyFromWindow:zb,encodeURI:encodeURI,encodeURIComponent:encodeURIComponent,getReferrer:Ab,getUrl:Bb,getUrlComponent:Cb,getUrlFragment:Db,isPlainObject:Eb,loadIframe:Fb,loadJavaScript:Gb,logToConsole:Hb,queryPermission:Ib,removeUrlFragment:Jb,replaceAll:Kb,sendPixel:Lb,setInWindow:Mb}};wb.prototype.L=function(a){return this.Va.L(a)};
wb.prototype.execute=wb.prototype.L;var vb=function(a,b){a.Va.V("require",b)};wb.prototype.oa=function(a){this.Va.oa(a)};wb.prototype.Na=function(a,b,c){this.Va.Na(a,b,c)};function xb(a,b){for(var c=a.split("."),d=z,e=d[c[0]],g=1;e&&g<c.length;g++)d=e,e=e[c[g]];if("function"==Ma(e)){var h=[];for(g=1;g<arguments.length;g++)h.push(Qa(arguments[g]));e.apply(d,h)}}function yb(a){var b=this.F();H(function(){a instanceof w&&a.o(b)})}function Bb(){return z.location.href}
function zb(a,b,c){for(var d=a.split("."),e=z,g=0;g<d.length-1;g++)if(e=e[d[g]],void 0===e||null===e)return;b&&(void 0===e[d[g]]||c&&!e[d[g]])&&(e[d[g]]=Qa(b));return Ra(e[d[g]])}function Ab(){return B.referrer}function Cb(a,b,c,d,e){var g;if(d&&d instanceof v){g=[];for(var h=0;h<d.length();h++){var k=d.get(h);"string"==typeof k&&g.push(k)}}return sb(N(a),b,c,g,e)}function Db(a){return sb(N(a),"fragment")}function Eb(a){return a instanceof Ka}
function Fb(a,b){var c=this.F();gb(a,function(){b instanceof w&&b.o(c)})}var Nb={};
function Gb(a,b,c,d){this.kb().assert("networkAccess",a);var e=this.F(),g=function(){b instanceof w&&b.o(e)},h=function(){c instanceof w&&c.o(e)};d?Nb[d]?(Nb[d].onSuccess.push(g),Nb[d].onFailure.push(h)):(Nb[d]={onSuccess:[g],onFailure:[h]},g=function(){for(var a=Nb[d].onSuccess,b=0;b<a.length;b++)H(a[b]);a.push=function(a){H(a);return 0}},h=function(){for(var a=Nb[d].onFailure,b=0;b<a.length;b++)H(a[b]);Nb[d]=null},fb(a,g,h)):fb(a,g,h)}
function Hb(){for(var a=Array.prototype.slice.call(arguments,0),b=0;b<a.length;b++)a[b]=Qa(a[b]);console.log.apply(console,a)}function Jb(a){return tb(N(a))}function Kb(a,b,c){return a.replace(new RegExp(b,"g"),c)}function Lb(a,b,c){this.kb().assert("sendPixel",a);var d=this.F();F(a,function(){b instanceof w&&b.o(d)},function(){c instanceof w&&c.o(d)})}
function Mb(a,b,c){for(var d=a.split("."),e=z,g=0;g<d.length-1;g++)if(e=e[d[g]],void 0===e)return!1;return void 0===e[d[g]]||c?(e[d[g]]=Qa(b),!0):!1}function Ib(a,b){try{return this.kb().assert.apply(null,Array.prototype.slice.call(arguments,0)),!0}catch(c){return!1}};
var Ob=[],Pb={"\x00":"&#0;",'"':"&quot;","&":"&amp;","'":"&#39;","<":"&lt;",">":"&gt;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;","-":"&#45;","/":"&#47;","=":"&#61;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"},Qb=function(a){return Pb[a]},Rb=/[\x00\x22\x26\x27\x3c\x3e]/g;Ob[3]=function(a){return String(a).replace(Rb,Qb)};var Xb=/[\x00\x08-\x0d\x22\x26\x27\/\x3c-\x3e\\\x85\u2028\u2029]/g,Yb={"\x00":"\\x00","\b":"\\x08","\t":"\\t","\n":"\\n","\x0B":"\\x0b",
"\f":"\\f","\r":"\\r",'"':"\\x22","&":"\\x26","'":"\\x27","/":"\\/","<":"\\x3c","=":"\\x3d",">":"\\x3e","\\":"\\\\","\u0085":"\\x85","\u2028":"\\u2028","\u2029":"\\u2029",$:"\\x24","(":"\\x28",")":"\\x29","*":"\\x2a","+":"\\x2b",",":"\\x2c","-":"\\x2d",".":"\\x2e",":":"\\x3a","?":"\\x3f","[":"\\x5b","]":"\\x5d","^":"\\x5e","{":"\\x7b","|":"\\x7c","}":"\\x7d"},Zb=function(a){return Yb[a]};
var gc=/[\x00- \x22\x27-\x29\x3c\x3e\\\x7b\x7d\x7f\x85\xa0\u2028\u2029\uff01\uff03\uff04\uff06-\uff0c\uff0f\uff1a\uff1b\uff1d\uff1f\uff20\uff3b\uff3d]/g,hc={"\x00":"%00","\u0001":"%01","\u0002":"%02","\u0003":"%03","\u0004":"%04","\u0005":"%05","\u0006":"%06","\u0007":"%07","\b":"%08","\t":"%09","\n":"%0A","\x0B":"%0B","\f":"%0C","\r":"%0D","\u000e":"%0E","\u000f":"%0F","\u0010":"%10",
"\u0011":"%11","\u0012":"%12","\u0013":"%13","\u0014":"%14","\u0015":"%15","\u0016":"%16","\u0017":"%17","\u0018":"%18","\u0019":"%19","\u001a":"%1A","\u001b":"%1B","\u001c":"%1C","\u001d":"%1D","\u001e":"%1E","\u001f":"%1F"," ":"%20",'"':"%22","'":"%27","(":"%28",")":"%29","<":"%3C",">":"%3E","\\":"%5C","{":"%7B","}":"%7D","\u007f":"%7F","\u0085":"%C2%85","\u00a0":"%C2%A0","\u2028":"%E2%80%A8","\u2029":"%E2%80%A9","\uff01":"%EF%BC%81","\uff03":"%EF%BC%83","\uff04":"%EF%BC%84","\uff06":"%EF%BC%86",
"\uff07":"%EF%BC%87","\uff08":"%EF%BC%88","\uff09":"%EF%BC%89","\uff0a":"%EF%BC%8A","\uff0b":"%EF%BC%8B","\uff0c":"%EF%BC%8C","\uff0f":"%EF%BC%8F","\uff1a":"%EF%BC%9A","\uff1b":"%EF%BC%9B","\uff1d":"%EF%BC%9D","\uff1f":"%EF%BC%9F","\uff20":"%EF%BC%A0","\uff3b":"%EF%BC%BB","\uff3d":"%EF%BC%BD"},ic=function(a){return hc[a]};var jc=
/^(?:(?:https?|mailto):|[^&:\/?#]*(?:[\/?#]|$))/i;Ob[14]=function(a){var b=String(a);return jc.test(b)?b.replace(gc,ic):"#zSoyz"};var kc,lc=[],mc=[],nc=[],oc=[],pc=[],qc={},rc,sc,tc,uc=function(a){var b=a["function"];if(!b)throw"Error: No function name given for function call.";var c=!!qc[b],d={},e;for(e in a)a.hasOwnProperty(e)&&0===e.indexOf("vtp_")&&(d[c?e:e.substr(4)]=a[e]);return c?qc[b](d):kc(b,d)},wc=function(a,b,c,d){c=c||[];d=d||qa;var e={},g;for(g in a)a.hasOwnProperty(g)&&(e[g]=vc(a[g],b,c,d));return e},xc=function(a){var b=a["function"];if(!b)throw"Error: No function name given for function call.";var c=qc[b];return c?
c.b||0:0},vc=function(a,b,c,d){if(ua(a)){var e;switch(a[0]){case "function_id":return a[1];case "list":e=[];for(var g=1;g<a.length;g++)e.push(vc(a[g],b,c,d));return e;case "macro":var h=a[1];if(c[h])return;var k=lc[h];if(!k||b(k))return;c[h]=!0;try{var l=wc(k,b,c,d);e=uc(l);tc&&(e=tc.sd(e,l))}catch(A){d(h,A),e=!1}c[h]=!1;return e;case "map":e={};for(var m=1;m<a.length;m+=2)e[vc(a[m],b,c,d)]=vc(a[m+1],b,c,d);return e;case "template":e=[];for(var n=!1,p=1;p<a.length;p++){var q=vc(a[p],b,c,d);sc&&(n=
n||q===sc.Ia);e.push(q)}return sc&&n?sc.td(e):e.join("");case "escape":e=vc(a[1],b,c,d);if(sc&&ua(a[1])&&"macro"===a[1][0]&&sc.$d(a))return sc.se(e);e=String(e);for(var r=2;r<a.length;r++)Ob[a[r]]&&(e=Ob[a[r]](e));return e;case "tag":var u=a[1];if(!oc[u])throw Error("Unable to resolve tag reference "+u+".");return e={bc:a[2],index:u};case "zb":var t=yc({"function":a[1],arg0:a[2],arg1:a[3],ignore_case:a[5]},b,c,d);a[4]&&(t=!t);return t;default:throw Error("Attempting to expand unknown Value type: "+
a[0]+".");}}return a},yc=function(a,b,c,d){try{return rc(wc(a,b,c,d))}catch(e){JSON.stringify(a)}return null};var Bc=null,Fc=function(a){function b(a){for(var b=0;b<a.length;b++)d[a[b]]=!0}var c=[],d=[];Bc=Cc(a,Dc()||function(){});for(var e=0;e<mc.length;e++){var g=mc[e],h=Ec(g);if(h){for(var k=g.add||[],l=0;l<k.length;l++)c[k[l]]=!0;b(g.block||[])}else null===h&&b(g.block||[])}var m=[];for(e=0;e<oc.length;e++)c[e]&&!d[e]&&(m[e]=!0);return m},Ec=function(a){for(var b=a["if"]||[],c=0;c<b.length;c++){var d=Bc(b[c]);if(!d)return null===d?null:!1}var e=a.unless||[];for(c=0;c<e.length;c++){d=Bc(e[c]);if(null===
d)return null;if(d)return!1}return!0};var Cc=function(a,b){var c=[];return function(d){void 0===c[d]&&(c[d]=yc(nc[d],a,void 0,b));return c[d]}};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var Ic={},Jc=null;Ic.s="GTM-M6N38SF";var Kc=null,Lc=null,Mc="//www.googletagmanager.com/a?id="+Ic.s+"&cv=13",Nc={},Oc={},Pc=B.currentScript?B.currentScript.src:void 0,Qc=function(){var a=Jc.sequence||0;Jc.sequence=a+1;return a};var P=function(){var a=function(a){return{toString:function(){return a}}};return{Kb:a("convert_case_to"),Lb:a("convert_false_to"),Mb:a("convert_null_to"),Nb:a("convert_true_to"),Ob:a("convert_undefined_to"),P:a("function"),Lc:a("instance_name"),Mc:a("live_only"),Nc:a("malware_disabled"),Oc:a("once_per_event"),Qb:a("once_per_load"),Rb:a("setup_tags"),Pc:a("tag_id"),Sb:a("teardown_tags")}}();var Rc=new Da,Sc={},Vc={set:function(a,b){Pa(Tc(a,b),Sc)},get:function(a){return Uc(a,2)},reset:function(){Rc=new Da;Sc={}}},Uc=function(a,b){return 2!=b?Rc.get(a):Wc(a)},Wc=function(a,b,c){var d=a.split(".");return Yc(d)},Yc=function(a){for(var b=Sc,c=0;c<a.length;c++){if(null===
b)return!1;if(void 0===b)break;b=b[a[c]]}return b};
var $c=function(a,b){Rc.set(a,b);Pa(Tc(a,b),Sc)},Tc=function(a,b){for(var c={},d=c,e=a.split("."),g=0;g<e.length-1;g++)d=d[e[g]]={};d[e[e.length-1]]=b;return c};var ad=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),bd={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},cd={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},dd=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c};
var ed=function(a){var b=Uc("gtm.whitelist");var c=b&&dd(Ba(b),bd),d=Uc("gtm.blacklist")||Uc("tagTypeBlacklist")||[];
ad.test(z.location&&z.location.hostname)&&(d=Ba(d),d.push("nonGooglePixels","nonGoogleScripts"));var e=d&&dd(Ba(d),cd),g={};return function(h){var k=h&&h[P.P];if(!k||"string"!=typeof k)return!0;k=k.replace(/^_*/,"");if(void 0!==g[k])return g[k];var l=Oc[k]||[],m=a(k);if(b){var n;if(n=m)a:{if(0>va(c,k))if(l&&0<l.length)for(var p=0;p<l.length;p++){if(0>va(c,l[p])){n=!1;break a}}else{n=!1;break a}n=!0}m=n}var q=!1;if(d){var r;if(!(r=0<=
va(e,k)))a:{for(var u=l||[],t=new Da,A=0;A<e.length;A++)t.set(e[A],!0);for(var C=0;C<u.length;C++)if(t.get(u[C])){r=!0;break a}r=!1}q=r}return g[k]=!m||q}};var fd={sd:function(a,b){b[P.Kb]&&"string"===typeof a&&(a=1==b[P.Kb]?a.toLowerCase():a.toUpperCase());b.hasOwnProperty(P.Mb)&&null===a&&(a=b[P.Mb]);b.hasOwnProperty(P.Ob)&&void 0===a&&(a=b[P.Ob]);b.hasOwnProperty(P.Nb)&&!0===a&&(a=b[P.Nb]);b.hasOwnProperty(P.Lb)&&!1===a&&(a=b[P.Lb]);return a}};var gd=function(a,b){this.oe=b};ia(gd,Error);gd.prototype.getParameters=function(){return this.oe};var hd=function(a){var b=Jc.zones;!b&&a&&(b=Jc.zones=a());return b},id={active:!0,isWhitelisted:function(){return!0}};var jd=!1,kd=0,ld=[];function md(a){if(!jd){var b=B.createEventObject,c="complete"==B.readyState,d="interactive"==B.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){jd=!0;for(var e=0;e<ld.length;e++)H(ld[e])}ld.push=function(){for(var a=0;a<arguments.length;a++)H(arguments[a]);return 0}}}function nd(){if(!jd&&140>kd){kd++;try{B.documentElement.doScroll("left"),md()}catch(a){z.setTimeout(nd,50)}}}var od=function(a){jd?a():ld.push(a)};var pd=!1,rd=function(){return z.GoogleAnalyticsObject&&z[z.GoogleAnalyticsObject]};
var sd=function(){function a(a){return!ta(a)||0>a?0:a}if(z.performance&&z.performance.timing){var b=z.performance.timing.navigationStart,c=ta(Vc.get("gtm.start"))?Vc.get("gtm.start"):0;Jc._li={cst:a(c-b),cbt:a(Kc-b)}}},td=function(a){z.GoogleAnalyticsObject||(z.GoogleAnalyticsObject=a||"ga");var b=z.GoogleAnalyticsObject;if(!z[b]){var c=function(){c.q=c.q||[];c.q.push(arguments)};c.l=Number(Ca());z[b]=c}sd();return z[b]},ud=function(a,b,c,d){b=String(b).replace(/\s+/g,"").split(",");var e=rd();e(a+
"require","linker");e(a+"linker:autoLink",b,c,d)};
var yd=function(){return"&tc="+oc.filter(function(a){return a}).length},zd="0.005000">Math.random(),Ad=function(){var a=0,b=0;return{ae:function(){if(2>a)return!1;1E3<=Ca().getTime()-b&&(a=0);return 2<=a},ze:function(){1E3<=Ca().getTime()-b&&(a=0);a++;b=Ca().getTime()}}},Bd="",Cd=function(){Bd=[Mc,"&v=3&t=t","&pid="+xa(),"&rv=a1"].join("")},Dd={},Ed="",Fd=void 0,Gd={},Hd={},Id=void 0,Jd=null,Kd=1E3,Ld=function(){var a=Fd;return void 0===a?"":[Bd,Dd[a]?"":"&es=1",
Gd[a],yd(),Ed,"&z=0"].join("")},Md=function(){Id&&(z.clearTimeout(Id),Id=void 0);void 0===Fd||Dd[Fd]&&!Ed||(Hd[Fd]||Jd.ae()||0>=Kd--?Hd[Fd]=!0:(Jd.ze(),F(Ld()),Dd[Fd]=!0,Ed=""))},Nd=function(a,b,c){if(zd&&!Hd[a]&&b){a!==Fd&&(Md(),Fd=a);var d=c+String(b[P.P]||"").replace(/_/g,"");Ed=Ed?Ed+"."+d:"&tr="+d;Id||(Id=z.setTimeout(Md,500));2022<=Ld().length&&Md()}};function Od(a,b,c,d,e,g){var h=oc[a],k=Pd(a,b,c,d,e,g);if(!k)return null;var l=vc(h[P.Rb],g.Y,[],Qd());if(l&&l.length){var m=l[0];k=Od(m.index,b,k,1===m.bc?e:k,e,g)}return k}
function Pd(a,b,c,d,e,g){function h(){var b=wc(k,g.Y,[],l);b.vtp_gtmOnSuccess=function(){Nd(g.id,oc[a],"5");c()};b.vtp_gtmOnFailure=function(){Nd(g.id,oc[a],"6");d()};b.vtp_gtmTagId=k.tag_id;if(k[P.Nc])d();else{Nd(g.id,k,"1");try{uc(b)}catch(C){Nd(g.id,
k,"7");e()}}}var k=oc[a];if(g.Y(k))return null;var l=Qd(),m=vc(k[P.Sb],g.Y,[],l);if(m&&m.length){var n=m[0],p=Od(n.index,b,c,d,e,g);if(!p)return null;c=p;d=2===n.bc?e:p}if(k[P.Qb]||k[P.Oc]){var q=k[P.Qb]?pc:b,r=c,u=d;if(!q[a]){h=Fa(h);var t=Rd(a,q,h);c=t.U;d=t.la}return function(){q[a](r,u)}}return h}
function Rd(a,b,c){var d=[],e=[];b[a]=Sd(d,e,c);return{U:function(){b[a]=Td;for(var c=0;c<d.length;c++)d[c]()},la:function(){b[a]=Ud;for(var c=0;c<e.length;c++)e[c]()}}}function Sd(a,b,c){return function(d,e){a.push(d);b.push(e);c()}}function Td(a){a()}function Ud(a,b){b()}function Qd(){return function(){}};function Vd(a){var b=0,c=0,d=!1;return{add:function(){c++;return Fa(function(){b++;d&&b>=c&&a()})},$c:function(){d=!0;b>=c&&a()}}}function Wd(a,b){var c,d=b.b,e=a.b;c=d>e?1:d<e?-1:0;var g;if(0!==c)g=c;else{var h=a.Jc,k=b.Jc;g=h>k?1:h<k?-1:0}return g}
function Xd(a,b){if(!zd)return;var c=function(a){var d=b.Y(oc[a])?"3":"4",g=vc(oc[a][P.Rb],b.Y,[],qa);g&&g.length&&c(g[0].index);Nd(b.id,oc[a],d);var h=vc(oc[a][P.Sb],b.Y,[],qa);h&&h.length&&c(h[0].index)};c(a);}var Yd=!1;function Dc(){return function(){}};var Zd=function(a,b){var c={};c[P.P]="__"+a;for(var d in b)b.hasOwnProperty(d)&&(c["vtp_"+d]=b[d]);for(d in void 0)(void 0).hasOwnProperty(d)&&(c[d]=(void 0)[d]);oc.push(c);return oc.length-1};var $d="allow_ad_personalization_signals cookie_domain cookie_expires cookie_name cookie_path custom_params event_callback event_timeout groups send_to send_page_view session_duration user_properties".split(" ");var ae=/[A-Z]+/,be=/\s/,ce=function(a){if(sa(a)&&(a=a.trim(),!be.test(a))){var b=a.indexOf("-");if(!(0>b)){var c=a.substring(0,b);if(ae.test(c)){for(var d=a.substring(b+1).split("/"),e=0;e<d.length;e++)if(!d[e])return;return{id:a,prefix:c,containerId:c+"-"+d[0],X:d}}}}};var de=null,ee={},fe={},ge;function he(){de=de||!Jc.gtagRegistered;Jc.gtagRegistered=!0;return de}var ie=function(a,b){var c={event:a};b&&(c.eventModel=Pa(b),b.event_callback&&(c.eventCallback=b.event_callback),b.event_timeout&&(c.eventTimeout=b.event_timeout));return c};
function je(a){if(void 0===fe[a.id]){var b;if("UA"==a.prefix)b=Zd("gtagua",{trackingId:a.id});else if("AW"==a.prefix)b=Zd("gtagaw",{conversionId:a});else if("DC"==a.prefix)b=Zd("gtagfl",{targetId:a.id});else if("GF"==a.prefix)b=Zd("gtaggf",{conversionId:a});else if("G"==a.prefix)b=Zd("get",{trackingId:a.id,isAutoTag:!0});else if("HA"==a.prefix)b=Zd("gtagha",{conversionId:a});else return;if(!ge){var c={name:"send_to",dataLayerVersion:2},d={};d[P.P]="__v";for(var e in c)c.hasOwnProperty(e)&&(d["vtp_"+
e]=c[e]);lc.push(d);ge=["macro",lc.length-1]}var g={arg0:ge,arg1:a.id,ignore_case:!1};g[P.P]="_lc";nc.push(g);var h={"if":[nc.length-1],add:[b]};h["if"]&&(h.add||h.block)&&mc.push(h);fe[a.id]=b}}
var le={event:function(a){var b=a[1];if(sa(b)&&!(3<a.length)){var c;if(2<a.length){if(!Oa(a[2]))return;c=a[2]}var d=ie(b,c);return d}},set:function(a){var b;2==a.length&&Oa(a[1])?
b=Pa(a[1]):3==a.length&&sa(a[1])&&(b={},b[a[1]]=a[2]);if(b)return b.eventModel=Pa(b),b.event="gtag.set",b._clear=!0,b},js:function(a){if(2==a.length&&a[1].getTime)return{event:"gtm.js","gtm.start":a[1].getTime()}},config:function(a){}},ke=Fa(function(){});var me=!1,ne=[];function oe(){if(!me){me=!0;for(var a=0;a<ne.length;a++)H(ne[a])}};var pe=[],qe=!1,re=function(a){var b=a.eventCallback,c=Fa(function(){ra(b)&&H(function(){b(Ic.s)})}),d=a.eventTimeout;d&&z.setTimeout(c,Number(d));return c},se=function(){for(var a=!1;!qe&&0<pe.length;){qe=!0;delete Sc.eventModel;var b=pe.shift();if(ra(b))try{b.call(Vc)}catch(De){}else if(ua(b)){var c=b;if(sa(c[0])){var d=c[0].split("."),e=d.pop(),g=c.slice(1),h=Uc(d.join("."),2);if(void 0!==h&&null!==h)try{h[e].apply(h,g)}catch(De){}}}else{var k=b;if(k&&("[object Arguments]"==Object.prototype.toString.call(k)||
Object.prototype.hasOwnProperty.call(k,"callee"))){a:{if(b.length&&sa(b[0])){var l=le[b[0]];if(l){b=l(b);break a}}b=void 0}if(!b){qe=!1;continue}}var m;var n=void 0,p=b,q=p._clear;for(n in p)p.hasOwnProperty(n)&&"_clear"!==n&&(q&&$c(n,void 0),$c(n,p[n]));var r=p.event;if(r){var u=p["gtm.uniqueEventId"];u||(u=Qc(),p["gtm.uniqueEventId"]=u,$c("gtm.uniqueEventId",u));Lc=r;var t;var A,C,D=p,L=D.event,E=D["gtm.uniqueEventId"],G=Jc.zones;C=G?G.checkState(Ic.s,E):id;if(C.active){var J=re(D);c:{var I=C.isWhitelisted;
if("gtm.js"==L){if(Yd){A=!1;break c}Yd=!0}var K=E,R=L;if(zd&&!Hd[K]&&Fd!==K){Md();Fd=K;Ed="";var ja=Gd,W=K,aa,M=R;aa=0===M.indexOf("gtm.")?encodeURIComponent(M):"*";ja[W]="&e="+aa+"&eid="+K;Id||(Id=z.setTimeout(Md,500))}var S=ed(I),O={id:E,name:L,callback:J||qa,Y:S,Da:[]};O.Da=Fc(S);for(var za,Za=O,Ub=Vd(Za.callback),zc=[],jb=[],$a=0;$a<oc.length;$a++)if(Za.Da[$a]){var Ee=oc[$a];var Vb=Ub.add();try{var Fe=Od($a,zc,Vb,Vb,Vb,Za);Fe?jb.push({Jc:$a,b:xc(Ee),L:Fe}):(Xd($a,Za),Vb())}catch(De){Vb()}}Ub.$c();jb.sort(Wd);for(var qd=0;qd<jb.length;qd++)jb[qd].L();za=0<jb.length;if("gtm.js"===L||"gtm.sync"===L)d:{}if(za){for(var Lg={__cl:!0,__evl:!0,__fsl:!0,__hl:!0,__jel:!0,__lcl:!0,__sdl:!0,__tl:!0,__ytl:!0},Ac=0;Ac<O.Da.length;Ac++)if(O.Da[Ac]){var He=oc[Ac];if(He&&!Lg[He[P.P]]){A=!0;break c}}A=!1}else A=za}t=A?!0:!1}else t=!1;Lc=null;m=t}else m=!1;a=m||a}qe=!1}return!a},te=function(){var a=se();try{var b=z["dataLayer"].hide;if(b&&void 0!==b[Ic.s]&&b.end){b[Ic.s]=!1;var c=!0,d;for(d in b)if(b.hasOwnProperty(d)&&
!0===b[d]){c=!1;break}c&&(b.end(),b.end=null)}}catch(e){}return a},ue=function(){var a=db("dataLayer",[]),b=db("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};ld.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});ne.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(pe.push.apply(pe,b);300<this.length;)this.shift();return se()};pe.push.apply(pe,a.slice(0));
H(te)};var ve={};ve.Ia=new String("undefined");ve.ab={};var we=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===ve.Ia?b:a[d]);return c.join("")}};we.prototype.toString=function(){return this.resolve("undefined")};we.prototype.valueOf=we.prototype.toString;ve.td=function(a){return new we(a)};var xe={};ve.Ae=function(a,b){var c=Qc();xe[c]=[a,b];return c};ve.Yb=function(a){var b=a?0:1;return function(a){var c=xe[a];if(c&&"function"===typeof c[b])c[b]();xe[a]=void 0}};
ve.$d=function(a){for(var b=!1,c=!1,d=2;d<a.length;d++)b=b||8===a[d],c=c||16===a[d];return b&&c};ve.se=function(a){if(a===ve.Ia)return a;var b=Qc();ve.ab[b]=a;return'google_tag_manager["'+Ic.s+'"].macro('+b+")"};ve.Qc=we;var ye=new Da,ze=function(a,b){function c(a){var b=N(a),c=sb(b,"protocol"),d=sb(b,"host",!0),e=sb(b,"port"),g=sb(b,"path").toLowerCase().replace(/\/$/,"");if(void 0===c||"http"==c&&"80"==e||"https"==c&&"443"==e)c="web",e="default";return[c,d,e,g]}for(var d=c(String(a)),e=c(String(b)),g=0;g<d.length;g++)if(d[g]!==e[g])return!1;return!0};
function Ae(a){var b=a.arg0,c=a.arg1;switch(a["function"]){case "_cn":return 0<=String(b).indexOf(String(c));case "_css":var d;a:{if(b){var e=["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector","oMatchesSelector"];try{for(var g=0;g<e.length;g++)if(b[e[g]]){d=b[e[g]](c);break a}}catch(u){}}d=!1}return d;case "_ew":var h,k;h=String(b);k=String(c);var l=h.length-k.length;return 0<=l&&h.indexOf(k,l)==l;case "_eq":return String(b)==String(c);case "_ge":return Number(b)>=Number(c);
case "_gt":return Number(b)>Number(c);case "_lc":var m;m=String(b).split(",");return 0<=va(m,String(c));case "_le":return Number(b)<=Number(c);case "_lt":return Number(b)<Number(c);case "_re":var n;var p=a.ignore_case?"i":void 0;try{var q=String(c)+p,r=ye.get(q);r||(r=new RegExp(c,p),ye.set(q,r));n=r.test(b)}catch(u){n=!1}return n;case "_sw":return 0==String(b).indexOf(String(c));case "_um":return ze(b,c)}return!1};var Be=function(){return!1};function Ce(a,b,c,d){return(d||"https:"==z.location.protocol?a:b)+c}function Ie(a,b){for(var c=b||(a instanceof v?new v:new Ka),d=a.T(),e=0;e<d.length();e++){var g=d.get(e);if(a.has(g)){var h=a.get(g);h instanceof v?(c.get(g)instanceof v||c.set(g,new v),Ie(h,c.get(g))):h instanceof Ka?(c.get(g)instanceof Ka||c.set(g,new Ka),Ie(h,c.get(g))):c.set(g,h)}}return c}function Je(){return Ic.s}function Ke(){return(new Date).getTime()}function Le(a,b){return Ra(Uc(a,b||2))}function Me(){return Lc}
function Ne(a){return nb('<a href="'+a+'"></a>')[0].href}function Oe(a){return ya(Qa(a))}function Pe(a){return null===a?"null":void 0===a?"undefined":a.toString()}function Qe(a,b){return xa(a,b)}function Re(a,b,c){if(!(a instanceof v))return null;for(var d=new Ka,e=!1,g=0;g<a.length();g++){var h=a.get(g);h instanceof Ka&&h.has(b)&&h.has(c)&&(d.set(h.get(b),h.get(c)),e=!0)}return e?d:null}
var Se=function(){var a=new bb,b=ub();Be()&&(b.loadJavaScript=qa,b.loadIframe=qa);a.addAll(b);a.addAll({buildSafeUrl:Ce,copy:Ie,copyFromDataLayer:Le,decodeHtmlUrl:Ne,generateRandom:Qe,generateUniqueNumber:Qc,getContainerId:Je,getCurrentTime:Ke,getEventName:Me,makeInteger:Oe,makeString:Pe,tableToMap:Re});return function(b){return a.get(b)}},Ue=function(){var a={networkAccess:Te};return function(b,c,d){return a[b]?a[b](c,d):qa}};
function Te(a,b){var c=a.url_list||[];return function(a,e){if(c.length){for(var d=0;d<c.length;d++)if(c[d]===e)return;throw b(a,{URL:e});}}};var Ve,Xe=function(){var a=data.runtime||[],b=data.permissions||{};Ve=new wb;kc=function(a,b){var c=new Ka,d;for(d in b)b.hasOwnProperty(d)&&c.set(d,Ra(b[d]));var e=Ve.L([a,c]);e instanceof f&&"return"===e.C&&(e=e.getData());return Qa(e)};rc=Ae;vb(Ve,Se());for(var c=0;c<a.length;c++){var d=a[c];if(!ua(d)||3>d.length){if(0==d.length)continue;return}Ve.L(d)}var e=function(a){throw We(a,{},"The requested permission is not configured.");};Ve.oa(e);var g=Ue(),h;for(h in b)if(b.hasOwnProperty(h)){var k=
b[h],l=!1,m;for(m in k)if(k.hasOwnProperty(m)){l=!0;var n=g(m,k[m],We);Ve.Na(h,m,n)}l||Ve.Na(h,"default",e)}};function We(a,b,c){return new gd(a,b,c)};var Ye=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var Ze=function(a){return encodeURIComponent(a)},$e=function(a,b){if(!a)return!1;var c=sb(N(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var g=c.length-e.length;0<g&&"."!=e.charAt(0)&&(g--,e="."+e);if(0<=g&&c.indexOf(e,g)==g)return!0}}return!1};
var Q=function(a,b,c){for(var d={},e=!1,g=0;a&&g<a.length;g++)a[g]&&a[g].hasOwnProperty(b)&&a[g].hasOwnProperty(c)&&(d[a[g][b]]=a[g][c],e=!0);return e?d:null},af=function(a,b){Pa(a,b)},bf=function(a){return ya(a)},cf=function(a,b){return va(a,b)};var df=function(a){var b={"gtm.element":a,"gtm.elementClasses":a.className,"gtm.elementId":a["for"]||kb(a,"id")||"","gtm.elementTarget":a.formTarget||a.target||""};b["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||a.href||a.src||a.code||a.codebase||"";return b},ef=function(a){Jc.hasOwnProperty("autoEventsSettings")||(Jc.autoEventsSettings={});var b=Jc.autoEventsSettings;b.hasOwnProperty(a)||(b[a]={});return b[a]},ff=function(a,b,c,d){var e=ef(a),g=Ea(e,b,d);e[b]=
c(g)},gf=function(a,b,c){var d=ef(a);return Ea(d,b,c)};var hf=!1;if(B.querySelectorAll)try{var jf=B.querySelectorAll(":root");jf&&1==jf.length&&jf[0]==B.documentElement&&(hf=!0)}catch(a){}var kf=hf;var lf=function(a,b,c){for(var d=[],e=String(b||document.cookie).split(";"),g=0;g<e.length;g++){var h=e[g].split("="),k=h[0].replace(/^\s*|\s*$/g,"");if(k&&k==a){var l=h.slice(1).join("=").replace(/^\s*|\s*$/g,"");l&&!0===c&&(l=decodeURIComponent(l));d.push(l)}}return d},of=function(a,b,c,d){var e=mf(a,d);if(1===e.length)return e[0].id;if(0!==e.length){e=nf(e,function(a){return a.Bd},b);if(1===e.length)return e[0].id;e=nf(e,function(a){return a.pe},c);return e[0]?e[0].id:void 0}},rf=function(a,b,
c,d,e,g){c=c||"/";var h=d=d||"auto",k=c;if(pf.test(document.location.hostname)||"/"===k&&qf.test(h))return!1;g&&(b=encodeURIComponent(b));var l=b;l&&1200<l.length&&(l=l.substring(0,1200));b=l;var m=a+"="+b+"; path="+c+"; ";void 0!==e&&(m+="expires="+e.toGMTString()+"; ");if("auto"===d){var n=!1,p;a:{var q=[],r=document.location.hostname.split(".");if(4===r.length){var u=r[r.length-1];if(parseInt(u,10).toString()===u){p=["none"];break a}}for(var t=r.length-2;0<=t;t--)q.push(r.slice(t).join("."));q.push("none");
p=q}for(var A=p,C=0;C<A.length&&!n;C++)n=rf(a,b,c,A[C],e);return n}d&&"none"!==d&&(m+="domain="+d+";");var D=document.cookie;document.cookie=m;return D!=document.cookie||0<=lf(a).indexOf(b)};function nf(a,b,c){for(var d=[],e=[],g,h=0;h<a.length;h++){var k=a[h],l=b(k);l===c?d.push(k):void 0===g||l<g?(e=[k],g=l):l===g&&e.push(k)}return 0<d.length?d:e}
function mf(a,b){for(var c=[],d=lf(a),e=0;e<d.length;e++){var g=d[e].split("."),h=g.shift();if(!b||-1!==b.indexOf(h)){var k=g.shift();k&&(k=k.split("-"),c.push({id:g.join("."),Bd:1*k[0]||1,pe:1*k[1]||1}))}}return c}var qf=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,pf=/(^|\.)doubleclick\.net$/i;var sf=window,tf=document;var uf=function(){for(var a=sf.navigator.userAgent+(tf.cookie||"")+(tf.referrer||""),b=a.length,c=sf.history.length;0<c;)a+=c--^b++;var d=1,e,g,h;if(a)for(d=0,g=a.length-1;0<=g;g--)h=a.charCodeAt(g),d=(d<<6&268435455)+h+(h<<14),e=d&266338304,d=0!=e?d^e>>21:d;return[Math.round(2147483647*Math.random())^d&2147483647,Math.round(Ca().getTime()/1E3)].join(".")},xf=function(a,b,c,d){var e=vf(b);return of(a,e,wf(c),d)};
function vf(a){if(!a)return 1;a=0===a.indexOf(".")?a.substr(1):a;return a.split(".").length}function wf(a){if(!a||"/"===a)return 1;"/"!==a[0]&&(a="/"+a);"/"!==a[a.length-1]&&(a+="/");return a.split("/").length-1}function yf(a,b){var c=""+vf(a),d=wf(b);1<d&&(c+="-"+d);return c};var zf=["1"],Af={},Ef=function(a,b,c){var d=Bf(a);Af[d]||Cf(d,b,c)||(Df(d,uf(),b,c),Cf(d,b,c))};function Df(a,b,c,d){var e;e=["1",yf(c,d),b].join(".");rf(a,e,d,c,new Date(Ca().getTime()+7776E6))}function Cf(a,b,c){var d=xf(a,b,c,zf);d&&(Af[a]=d);return d}function Bf(a){return(a||"_gcl")+"_au"};function Ff(){for(var a=Gf,b={},c=0;c<a.length;++c)b[a[c]]=c;return b}function Hf(){var a="ABCDEFGHIJKLMNOPQRSTUVWXYZ";a+=a.toLowerCase()+"0123456789-_";return a+"."}
var Gf,If,Jf=function(a){Gf=Gf||Hf();If=If||Ff();for(var b=[],c=0;c<a.length;c+=3){var d=c+1<a.length,e=c+2<a.length,g=a.charCodeAt(c),h=d?a.charCodeAt(c+1):0,k=e?a.charCodeAt(c+2):0,l=g>>2,m=(g&3)<<4|h>>4,n=(h&15)<<2|k>>6,p=k&63;e||(p=64,d||(n=64));b.push(Gf[l],Gf[m],Gf[n],Gf[p])}return b.join("")},Kf=function(a){function b(b){for(;d<a.length;){var c=a.charAt(d++),e=If[c];if(null!=e)return e;if(!/^[\s\xa0]*$/.test(c))throw Error("Unknown base64 encoding at char: "+c);}return b}Gf=Gf||Hf();If=If||
Ff();for(var c="",d=0;;){var e=b(-1),g=b(0),h=b(64),k=b(64);if(64===k&&-1===e)return c;c+=String.fromCharCode(e<<2|g>>4);64!=h&&(c+=String.fromCharCode(g<<4&240|h>>2),64!=k&&(c+=String.fromCharCode(h<<6&192|k)))}};var Lf;function Mf(a,b){if(!a||b===B.location.hostname)return!1;for(var c=0;c<a.length;c++)if(a[c]instanceof RegExp){if(a[c].test(b))return!0}else if(0<=b.indexOf(a[c]))return!0;return!1}var Nf=function(){var a=db("google_tag_data",{}),b=a.gl;b&&b.decorators||(b={decorators:[]},a.gl=b);return b};var Of=/(.*?)\*(.*?)\*(.*)/,Pf=/([^?#]+)(\?[^#]*)?(#.*)?/,Qf=/(.*?)(^|&)_gl=([^&]*)&?(.*)/,Sf=function(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];void 0!==d&&d===d&&null!==d&&"[object Object]"!==d.toString()&&(b.push(c),b.push(Jf(String(d))))}var e=b.join("*");return["1",Rf(e),e].join("*")},Rf=function(a,b){var c=[window.navigator.userAgent,(new Date).getTimezoneOffset(),window.navigator.userLanguage||window.navigator.language,Math.floor((new Date).getTime()/60/1E3)-(void 0===b?0:
b),a].join("*"),d;if(!(d=Lf)){for(var e=Array(256),g=0;256>g;g++){for(var h=g,k=0;8>k;k++)h=h&1?h>>>1^3988292384:h>>>1;e[g]=h}d=e}Lf=d;for(var l=4294967295,m=0;m<c.length;m++)l=l>>>8^Lf[(l^c.charCodeAt(m))&255];return((l^-1)>>>0).toString(36)},Uf=function(){return function(a){var b=N(z.location.href),c=b.search.replace("?",""),d=rb(c,"_gl",!0)||"";a.query=Tf(d)||{};var e=sb(b,"fragment").match(Qf);a.fragment=Tf(e&&e[3]||"")||{}}},Tf=function(a){var b;b=void 0===b?3:b;try{if(a){var c=Of.exec(a);if(c&&
"1"===c[1]){var d=c[3],e;a:{for(var g=c[2],h=0;h<b;++h)if(g===Rf(d,h)){e=!0;break a}e=!1}if(e){for(var k={},l=d?d.split("*"):[],m=0;m<l.length;m+=2)k[l[m]]=Kf(l[m+1]);return k}}}}catch(n){}};
function Vf(a,b,c){function d(a){var b=a,c=Qf.exec(b),d=b;if(c){var e=c[2],g=c[4];d=c[1];g&&(d=d+e+g)}a=d;var h=a.charAt(a.length-1);a&&"&"!==h&&(a+="&");return a+l}c=void 0===c?!1:c;var e=Pf.exec(b);if(!e)return"";var g=e[1],h=e[2]||"",k=e[3]||"",l="_gl="+a;c?k="#"+d(k.substring(1)):h="?"+d(h.substring(1));return""+g+h+k}
function Wf(a,b,c){for(var d={},e={},g=Nf().decorators,h=0;h<g.length;++h){var k=g[h];(!c||k.forms)&&Mf(k.domains,b)&&(k.fragment?Ga(e,k.callback()):Ga(d,k.callback()))}if(Ha(d)){var l=Sf(d);if(c){if(a&&a.action){var m=(a.method||"").toLowerCase();if("get"===m){for(var n=a.childNodes||[],p=!1,q=0;q<n.length;q++){var r=n[q];if("_gl"===r.name){r.setAttribute("value",l);p=!0;break}}if(!p){var u=B.createElement("input");u.setAttribute("type","hidden");u.setAttribute("name","_gl");u.setAttribute("value",
l);a.appendChild(u)}}else if("post"===m){var t=Vf(l,a.action);pb.test(t)&&(a.action=t)}}}else Xf(l,a,!1)}if(!c&&Ha(e)){var A=Sf(e);Xf(A,a,!0)}}function Xf(a,b,c){if(b.href){var d=Vf(a,b.href,void 0===c?!1:c);pb.test(d)&&(b.href=d)}}
var Yf=function(a){try{var b;a:{for(var c=a.target||a.srcElement||{},d=100;c&&0<d;){if(c.href&&c.nodeName.match(/^a(?:rea)?$/i)){b=c;break a}c=c.parentNode;d--}b=null}var e=b;if(e){var g=e.protocol;"http:"!==g&&"https:"!==g||Wf(e,e.hostname,!1)}}catch(h){}},Zf=function(a){try{var b=a.target||a.srcElement||{};if(b.action){var c=sb(N(b.action),"host");Wf(b,c,!0)}}catch(d){}},$f=function(a,b,c,d){var e=Nf();e.init||(hb(B,"mousedown",Yf),hb(B,"keyup",Yf),hb(B,"submit",Zf),e.init=!0);var g={callback:a,
domains:b,fragment:"fragment"===c,forms:!!d};Nf().decorators.push(g)};var ag=/^\w+$/,bg=/^[\w-]+$/,cg=/^~?[\w-]+$/,dg={aw:"_aw",dc:"_dc",gf:"_gf",ha:"_ha"},fg=function(a){var b=lf(a,B.cookie),c=[];if(!b||0==b.length)return c;for(var d=0;d<b.length;d++){var e=b[d].split(".");3==e.length&&"GCL"==e[0]&&e[1]&&c.push(e[2])}return eg(c)};function gg(a){return a&&"string"==typeof a&&a.match(ag)?a:"_gcl"}
var hg=function(a){if(a){if("string"==typeof a){var b=gg(a);return{dc:b,aw:b,gf:b,ha:b}}if(a&&"object"==typeof a)return{dc:gg(a.dc),aw:gg(a.aw),gf:gg(a.gf),ha:gg(a.ha)}}return{dc:"_gcl",aw:"_gcl",gf:"_gcl",ha:"_gcl"}},ig=function(){var a=N(z.location.href),b={},c=function(a,c){b[c]||(b[c]=[]);b[c].push(a)},d=sb(a,"query",!1,void 0,"gclid"),e=sb(a,"query",!1,void 0,"gclsrc");if(!d||!e){var g=a.hash.replace("#","");d=d||rb(g,"gclid");e=e||rb(g,"gclsrc")}if(void 0!==d&&d.match(bg))switch(e){case void 0:c(d,
"aw");break;case "aw.ds":c(d,"aw");c(d,"dc");break;case "ds":c(d,"dc");break;case "gf":c(d,"gf");break;case "ha":c(d,"ha")}var h=sb(a,"query",!1,void 0,"dclid");h&&c(h,"dc");return b},kg=function(a){function b(a,b){var g=jg(a,c);g&&rf(g,b,e,d,h,!0)}a=a||{};var c=hg(a.prefix),d=a.domain||"auto",e=a.path||"/",g=Ca().getTime(),h=new Date(g+7776E6),k=Math.round(g/1E3),l=ig(),m=function(a){return["GCL",k,a].join(".")};l.aw&&(!0===a.vf?b("aw",m("~"+l.aw[0])):b("aw",m(l.aw[0])));l.dc&&b("dc",m(l.dc[0]));
l.gf&&b("gf",m(l.gf[0]));l.ha&&b("ha",m(l.ha[0]))},jg=function(a,b){var c=dg[a];if(void 0!==c){var d=b[a];if(void 0!==d)return d+c}},lg=function(a){var b=a.split(".");return 3!==b.length||"GCL"!==b[0]?0:1E3*(Number(b[1])||0)},mg=function(a,b,c,d,e){if(ua(b)){var g=hg(e);$f(function(){for(var b={},c=0;c<a.length;++c){var d=jg(a[c],g);if(d){var e=lf(d,B.cookie);e.length&&(b[d]=e.sort()[e.length-1])}}return b},b,c,d)}},eg=function(a){return a.filter(function(a){return cg.test(a)})};var ng=/^\d+\.fls\.doubleclick\.net$/;function og(a){var b=N(z.location.href),c=sb(b,"host",!1);if(c&&c.match(ng)){var d=sb(b,"path").split(a+"=");if(1<d.length)return d[1].split(";")[0].split("?")[0]}}
var pg=function(a){var b=og("gclaw");if(b)return b.split(".");var c=hg(a);if("_gcl"==c.aw){var d=ig().aw||[];if(0<d.length)return d}var e=jg("aw",c);return e?fg(e):[]},qg=function(a){var b=og("gcldc");if(b)return b.split(".");var c=hg(a);if("_gcl"==c.dc){var d=ig().dc||[];if(0<d.length)return d}var e=jg("dc",c);return e?fg(e):[]},rg=function(a){var b=hg(a);if("_gcl"==b.ha){var c=ig().ha||[];if(0<c.length)return c}return fg(b.ha+"_ha")},sg=function(){var a=og("gac");if(a)return decodeURIComponent(a);
for(var b=[],c=B.cookie.split(";"),d=/^\s*_gac_(UA-\d+-\d+)=\s*(.+?)\s*$/,e=0;e<c.length;e++){var g=c[e].match(d);g&&b.push({Cb:g[1],value:g[2]})}var h={};if(b&&b.length)for(var k=0;k<b.length;k++){var l=b[k].value.split(".");"1"==l[0]&&3==l.length&&l[1]&&(h[b[k].Cb]||(h[b[k].Cb]=[]),h[b[k].Cb].push({timestamp:l[1],Id:l[2]}))}var m=[],n;for(n in h)if(h.hasOwnProperty(n)){for(var p=[],q=h[n],r=0;r<q.length;r++)p.push(q[r].Id);p=eg(p);p.length&&m.push(n+":"+p.join(","))}return m.join(";")},tg=function(a,
b,c){Ef(a,b,c);var d=Af[Bf(a)],e=ig().dc||[];if(d&&0<e.length){var g=Jc.joined_au=Jc.joined_au||{},h=a||"_gcl";if(!g[h]){for(var k=!1,l=0;l<e.length;l++){var m="https://adservice.google.com/ddm/regclk";m+="?gclid="+e[l]+"&auiddc="+d;ob(m);k=!0}if(k){var n=Bf(a);Af[n]&&Df(n,Af[n],b,c);g[h]=!0}}}};var ug;a:{ug="G"}var vg={"":"n",UA:"u",AW:"a",DC:"d",G:"e",GTM:ug},wg=function(a){var b=Ic.s.split("-"),c=b[0].toUpperCase();return(vg[c]||"i")+"a1"+(a&&"GTM"===c?b[1]:"")};var Dg=!!z.MutationObserver,Eg=void 0,Fg=function(a){if(!Eg){var b=function(){var a=B.body;if(a)if(Dg)(new MutationObserver(function(){for(var a=0;a<Eg.length;a++)H(Eg[a])})).observe(a,{childList:!0,subtree:!0});else{var b=!1;hb(a,"DOMNodeInserted",function(){b||(b=!0,H(function(){b=!1;for(var a=0;a<Eg.length;a++)H(Eg[a])}))})}};Eg=[];B.body?b():H(b)}Eg.push(a)};var Qg="www.googletagmanager.com/gtm.js";
var Rg=Qg,Sg=function(a,b,c,d){hb(a,b,c,d)},Tg=function(a,b){return z.setTimeout(a,b)},T=function(a,b,c){if(Be()){b&&H(b)}else return fb(a,b,c)},Ug=function(){return z.location.href},Vg=function(a){return sb(N(a),"fragment")},Wg=function(a,b,c,d,e){return sb(a,b,c,d,e)},U=function(a,b){return Uc(a,b||2)},Xg=function(a,b,c){b&&(a.eventCallback=b,c&&(a.eventTimeout=c));return z["dataLayer"].push(a)},Yg=function(a,
b){z[a]=b},V=function(a,b,c){b&&(void 0===z[a]||c&&!z[a])&&(z[a]=b);return z[a]},Zg=function(a,b,c){return lf(a,b,void 0===c?!0:!!c)},$g=function(a,b,c){kg({prefix:a,path:b,domain:c})},ah=function(a,b,c,d){var e=Uf(),g=Nf();g.data||(g.data={query:{},fragment:{}},e(g.data));var h={},k=g.data;k&&(Ga(h,k.query),Ga(h,k.fragment));for(var l=hg(b),m=0;m<a.length;++m){var n=a[m];if(void 0!==dg[n]){var p=jg(n,l),q=h[p];if(q){var r=Math.min(lg(q),Ca().getTime()),
u;b:{for(var t=r,A=lf(p,B.cookie),C=0;C<A.length;++C)if(lg(A[C])>t){u=!0;break b}u=!1}u||rf(p,q,c,d,new Date(r+7776E6),!0)}}}},bh=function(a,b,c,d,e){mg(a,b,c,d,e);},ch=function(a,b){var c;a:{var d;d=100;for(var e={},g=0;g<b.length;g++)e[b[g]]=!0;for(var h=a,k=0;h&&k<=d;k++){if(e[String(h.tagName).toLowerCase()]){c=h;break a}h=h.parentElement}c=null}return c},X=function(a,
b,c,d){var e=!d&&"http:"==z.location.protocol;e&&(e=2!==dh());return(e?b:a)+c},eh=function(a,b){if(Be()){b&&H(b)}else gb(a,b)};
var fh=function(a){var b=0;return b},gh=function(a){},hh=function(a){var b=!1;return b},ih=function(a,b){var c;a:{if(a&&
ua(a))for(var d=0;d<a.length;d++)if(a[d]&&b(a[d])){c=a[d];break a}c=void 0}return c},jh=function(a,b,c,d){ff(a,b,c,d)},kh=function(a,b,c){return gf(a,b,c)},lh=function(a){return!!gf(a,"init",!1)},mh=function(a){ef(a).init=!0};
var dh=function(){var a=Rg;if(Pc){if(0===Pc.toLowerCase().indexOf("https://"))return 2;if(0===Pc.toLowerCase().indexOf("http://"))return 3}a=a.toLowerCase();for(var b="https://"+a,c="http://"+a,d=1,e=B.getElementsByTagName("script"),g=0;g<e.length&&100>g;g++){var h=e[g].src;if(h){h=h.toLowerCase();if(0===h.indexOf(c))return 3;1===d&&0===h.indexOf(b)&&(d=2)}}return d};
var qh=function(a,b,c){var d=(void 0===c?0:c)?"www.googletagmanager.com/gtag/js":Rg;d+="?id="+encodeURIComponent(a)+"&l=dataLayer";if(b)for(var e in b)b[e]&&b.hasOwnProperty(e)&&(d+="&"+e+"="+encodeURIComponent(b[e]));T(X("https://","http://",d))};
var sh=function(a,b,c){a instanceof ve.Qc&&(a=a.resolve(ve.Ae(b,c)),b=qa);return{mb:a,U:b}};var Fh=function(a,b,c){this.n=a;this.t=b;this.p=c},Gh=function(){this.c=1;this.e=[];this.p=null};function Hh(a){var b=Jc,c=b.gss=b.gss||{};return c[a]=c[a]||new Gh}var Ih=function(a,b){Hh(a).p=b},Jh=function(a,b,c){var d=Math.floor(Ca().getTime()/1E3);Hh(a).e.push(new Fh(b,d,c))},Kh=function(a){};var Th=window,Uh=document,Vh=function(a){var b=Th._gaUserPrefs;if(b&&b.ioo&&b.ioo()||a&&!0===Th["ga-disable-"+a])return!0;try{var c=Th.external;if(c&&c._gaUserPrefs&&"oo"==c._gaUserPrefs)return!0}catch(g){}for(var d=lf("AMP_TOKEN",Uh.cookie,!0),e=0;e<d.length;e++)if("$OPT_OUT"==d[e])return!0;return!1};var $h=function(a){if(1===Hh(a).c){Hh(a).c=2;var b=encodeURIComponent(a);fb(("http:"!=z.location.protocol?"https:":"http:")+("//www.googletagmanager.com/gtag/js?id="+b+"&l=dataLayer&cx=c"))}},ai=function(a,b){};var Z={a:{}};
Z.a.e=["google"],function(){(function(a){Z.__e=a;Z.__e.g="e";Z.__e.h=!0;Z.__e.b=0})(function(){return Lc})}();Z.a.f=["google"],function(){(function(a){Z.__f=a;Z.__f.g="f";Z.__f.h=!0;Z.__f.b=0})(function(a){var b=U("gtm.referrer",1)||B.referrer;return b?a.vtp_component&&"URL"!=a.vtp_component?Wg(N(String(b)),a.vtp_component,a.vtp_stripWww,a.vtp_defaultPages,a.vtp_queryKey):tb(N(String(b))):String(b)})}();


Z.a.u=["google"],function(){var a=function(a){return{toString:function(){return a}}};(function(a){Z.__u=a;Z.__u.g="u";Z.__u.h=!0;Z.__u.b=0})(function(b){var c;c=(c=b.vtp_customUrlSource?b.vtp_customUrlSource:U("gtm.url",1))||Ug();var d=b[a("vtp_component")];return d&&"URL"!=d?Wg(N(String(c)),d,"HOST"==d?b[a("vtp_stripWww")]:void 0,"PATH"==d?b[a("vtp_defaultPages")]:void 0,"QUERY"==d?b[a("vtp_queryKey")]:void 0):tb(N(String(c)))})}();
Z.a.v=["google"],function(){(function(a){Z.__v=a;Z.__v.g="v";Z.__v.h=!0;Z.__v.b=0})(function(a){var b=a.vtp_name;if(!b||!b.replace)return!1;var c=U(b.replace(/\\\./g,"."),a.vtp_dataLayerVersion||1);return void 0!==c?c:a.vtp_defaultValue})}();
Z.a.ua=["google"],function(){var a,b=function(b){var c={},e={},g={},h={},k={};if(b.vtp_gaSettings){var l=b.vtp_gaSettings;af(Q(l.vtp_fieldsToSet,"fieldName","value"),e);af(Q(l.vtp_contentGroup,"index","group"),g);af(Q(l.vtp_dimension,"index","dimension"),h);af(Q(l.vtp_metric,"index","metric"),k);b.vtp_gaSettings=null;l.vtp_fieldsToSet=void 0;l.vtp_contentGroup=void 0;l.vtp_dimension=void 0;l.vtp_metric=void 0;var m=Pa(l,void 0);b=Pa(b,m)}af(Q(b.vtp_fieldsToSet,"fieldName","value"),e);af(Q(b.vtp_contentGroup,
"index","group"),g);af(Q(b.vtp_dimension,"index","dimension"),h);af(Q(b.vtp_metric,"index","metric"),k);var n=td(b.vtp_functionName),p="",q="";b.vtp_setTrackerName&&"string"==typeof b.vtp_trackerName?""!==b.vtp_trackerName&&(q=b.vtp_trackerName,p=q+"."):(q="gtm"+Qc(),p=q+".");var r={name:!0,clientId:!0,sampleRate:!0,siteSpeedSampleRate:!0,alwaysSendReferrer:!0,allowAnchor:!0,allowLinker:!0,cookieName:!0,cookieDomain:!0,cookieExpires:!0,cookiePath:!0,cookieUpdate:!0,legacyCookieDomain:!0,legacyHistoryImport:!0,
storage:!0,useAmpClientId:!0,storeGac:!0},u={allowAnchor:!0,allowLinker:!0,alwaysSendReferrer:!0,anonymizeIp:!0,cookieUpdate:!0,exFatal:!0,forceSSL:!0,javaEnabled:!0,legacyHistoryImport:!0,nonInteraction:!0,useAmpClientId:!0,useBeacon:!0,storeGac:!0,allowAdFeatures:!0},t=function(a){var b=[].slice.call(arguments,0);b[0]=p+b[0];n.apply(window,b)},A=function(a,b){return void 0===b?b:a(b)},C=function(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&t("set",a+c,b[c])},D=function(){},L=function(a,b,c){var d=0;if(a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&r[e]||!c&&void 0===r[e])){var g=u[e]?Aa(a[e]):a[e];"anonymizeIp"!=e||g||(g=void 0);b[e]=g;d++}return d},E={name:q};L(e,E,
!0);n("create",b.vtp_trackingId||c.trackingId,E);t("set","&gtm",wg(!0));(function(a,c){void 0!==b[c]&&t("set",a,b[c])})("nonInteraction","vtp_nonInteraction");C("contentGroup",g);C("dimension",h);C("metric",k);var G={};L(e,G,!1)&&t("set",G);var J;b.vtp_enableLinkId&&t("require","linkid","linkid.js");t("set","hitCallback",function(){var a=
e&&e.hitCallback;ra(a)&&a();b.vtp_gtmOnSuccess()});if("TRACK_EVENT"==b.vtp_trackType){}else if("TRACK_SOCIAL"==
b.vtp_trackType){}else if("TRACK_TRANSACTION"==b.vtp_trackType){}else if("TRACK_TIMING"==b.vtp_trackType){}else if("DECORATE_LINK"==b.vtp_trackType){}else if("DECORATE_FORM"==b.vtp_trackType){}else if("TRACK_DATA"==
b.vtp_trackType){}else{b.vtp_enableEcommerce&&(t("require","ec","ec.js"),D());if(b.vtp_doubleClick||"DISPLAY_FEATURES"==b.vtp_advertisingFeaturesType){var S="_dc_gtm_"+String(b.vtp_trackingId).replace(/[^A-Za-z0-9-]/g,"");t("require","displayfeatures",void 0,{cookieName:S})}"DISPLAY_FEATURES_WITH_REMARKETING_LISTS"==b.vtp_advertisingFeaturesType&&
(S="_dc_gtm_"+String(b.vtp_trackingId).replace(/[^A-Za-z0-9-]/g,""),t("require","adfeatures",{cookieName:S}));J?t("send","pageview",J):t("send","pageview");}if(!a){var O=b.vtp_useDebugVersion?"u/analytics_debug.js":"analytics.js";b.vtp_useInternalVersion&&!b.vtp_useDebugVersion&&
(O="internal/"+O);a=!0;T(X("https:","http:","//www.google-analytics.com/"+O,e&&e.forceSSL),function(){var a=rd();a&&a.loaded||b.vtp_gtmOnFailure();},b.vtp_gtmOnFailure)}};Z.__ua=b;Z.__ua.g="ua";Z.__ua.h=!0;Z.__ua.b=0}();

Z.a.qcm=["nonGoogleScripts"],function(){(function(a){Z.__qcm=a;Z.__qcm.g="qcm";Z.__qcm.h=!0;Z.__qcm.b=0})(function(a){V("_qevents",[],!0).push({qacct:a.vtp_pcode,labels:a.vtp_labels||""});var b=X("https://secure","http://edge",".quantserve.com/quant.js");T(b,a.vtp_gtmOnSuccess,a.vtp_gtmOnFailure)})}();


Z.a.gas=["google"],function(){(function(a){Z.__gas=a;Z.__gas.g="gas";Z.__gas.h=!0;Z.__gas.b=0})(function(a){var b=Pa(a,void 0),c=b;c[P.P]=null;c[P.Lc]=null;var d=b=c;d.vtp_fieldsToSet=d.vtp_fieldsToSet||[];var e=d.vtp_cookieDomain;void 0!==e&&(d.vtp_fieldsToSet.push({fieldName:"cookieDomain",value:e}),delete d.vtp_cookieDomain);return b})}();





Z.a.html=["customScripts"],function(){var a=function(b,c,g,h){return function(){try{if(0<c.length){var d=c.shift(),e=a(b,c,g,h);if("SCRIPT"==String(d.nodeName).toUpperCase()&&"text/gtmscript"==d.type){var m=B.createElement("script");m.async=!1;m.type="text/javascript";m.id=d.id;m.text=d.text||d.textContent||d.innerHTML||"";d.charset&&(m.charset=d.charset);var n=d.getAttribute("data-gtmsrc");n&&(m.src=n,eb(m,e));b.insertBefore(m,null);n||e()}else if(d.innerHTML&&0<=d.innerHTML.toLowerCase().indexOf("<script")){for(var p=
[];d.firstChild;)p.push(d.removeChild(d.firstChild));b.insertBefore(d,null);a(d,p,e,h)()}else b.insertBefore(d,null),e()}else g()}catch(q){H(h)}}};var c=function(d){if(B.body){var e=
d.vtp_gtmOnFailure,g=sh(d.vtp_html,d.vtp_gtmOnSuccess,e),h=g.mb,k=g.U;if(d.vtp_useIframe){}else d.vtp_supportDocumentWrite?b(h,k,e):a(B.body,nb(h),k,e)()}else Tg(function(){c(d)},200)};Z.__html=c;Z.__html.g="html";Z.__html.h=!0;Z.__html.b=
0}();
Z.a.img=["customPixels"],function(){(function(a){Z.__img=a;Z.__img.g="img";Z.__img.h=!0;Z.__img.b=0})(function(a){var b=nb('<a href="'+a.vtp_url+'"></a>')[0].href,c=a.vtp_cacheBusterQueryParam;if(a.vtp_useCacheBuster){c||(c="gtmcb");var d=b.charAt(b.length-1),e=0<=b.indexOf("?")?"?"==d||"&"==d?"":"&":"?";b+=e+c+"="+a.vtp_randomNumber}F(b,a.vtp_gtmOnSuccess,a.vtp_gtmOnFailure)})}();



Z.a.csm=["nonGoogleScripts"],function(){(function(a){Z.__csm=a;Z.__csm.g="csm";Z.__csm.h=!0;Z.__csm.b=0})(function(a){var b=V("document");F(function(a){if(2048<a.length){var b=a.substring(0,2040).lastIndexOf("&");a=a.substring(0,b)+"&ns_cut="+encodeURIComponent(a.substring(b+1));a=a.substring(0,2048)}return a}(function(a,c){var d=new Date,e=(c||"").split("&");c="";for(var k=0;k<e.length;k++)if(e[k]){var l=e[k].match(/([^=]*)=?(.*)/);c+="&"+encodeURIComponent(l[1])+"="+encodeURIComponent(l[2])}return X("https://sb",
"http://b",".scorecardresearch.com/b?c1=2&c2="+encodeURIComponent(a)+"&ns__t="+d.valueOf()+"&ns_c="+(b.characterSet||b.defaultCharset||"")+"&c8="+encodeURIComponent(b.title||"")+c+"&c7="+encodeURIComponent(b.URL)+"&c9="+encodeURIComponent(b.referrer))}(a.vtp_clientId,function(){var a="",c=b.cookie;if(0<=c.indexOf("comScore"))for(var g=c.split(";"),h=0;h<g.length;h++){var k=g[h].indexOf("comScore");0<=k&&(a=unescape(g[h].substring(k+8)))}return a}())),void 0,void 0);var c=function(){var b=X("https://sb",
"http://b",".scorecardresearch.com/c2/"+encodeURIComponent(a.vtp_clientId)+"/cs.js");T(b,a.vtp_gtmOnSuccess,a.vtp_gtmOnFailure)};"complete"===b.readyState?c():Sg(V("self"),"load",c)})}();var bi={macro:function(a){if(ve.ab.hasOwnProperty(a))return ve.ab[a]}};bi.dataLayer=Vc;bi.onHtmlSuccess=ve.Yb(!0);bi.onHtmlFailure=ve.Yb(!1);bi.callback=function(a){Nc.hasOwnProperty(a)&&ra(Nc[a])&&Nc[a]();delete Nc[a]};bi.ed=function(){Jc[Ic.s]=bi;Oc=Z.a;sc=sc||ve;tc=fd};
bi.Wd=function(){Jc=z.google_tag_manager=z.google_tag_manager||{};if(Jc[Ic.s]){var a=Jc.zones;a&&a.unregisterChild(Ic.s)}else{for(var b=data.resource||{},c=b.macros||[],d=0;d<c.length;d++)lc.push(c[d]);for(var e=b.tags||[],g=0;g<e.length;g++)oc.push(e[g]);for(var h=b.predicates||[],k=0;k<h.length;k++)nc.push(h[k]);for(var l=b.rules||[],m=0;m<l.length;m++){for(var n=l[m],p={},q=0;q<n.length;q++)p[n[q][0]]=Array.prototype.slice.call(n[q],1);mc.push(p)}qc=Z;Xe();bi.ed();ue();jd=!1;kd=0;if("interactive"==
B.readyState&&!B.createEventObject||"complete"==B.readyState)md();else{hb(B,"DOMContentLoaded",md);hb(B,"readystatechange",md);if(B.createEventObject&&B.documentElement.doScroll){var r=!0;try{r=!z.frameElement}catch(t){}r&&nd()}hb(z,"load",md)}me=!1;"complete"===B.readyState?oe():hb(z,"load",oe);a:{
if(!zd)break a;Cd();Fd=void 0;Gd={};Dd={};Id=void 0;Hd={};Ed="";Jd=Ad();z.setInterval(Cd,864E5);}Kc=(new Date).getTime()}};bi.Wd();

})()
